export interface AuthoritiesUtilisateur {

  DELETE_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE:boolean;
  VIEW_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE  :boolean;
  
//Ordre de mission
ADD_ORDRE_MISSION:boolean;
VIEW_ORDRE_MISSION :boolean;  
MODIFY_ORDRE_MISSION:boolean;
DELETE_ORDRE_MISSION:boolean; 
VEHICULE_ORDRE_MISSION:boolean;
CONFIRMER_ORDRE_MISSION:boolean;
VEHICULE_VEHICULE_DEPASSANT:boolean;
VIEW_VEHICULE_DEPASSANT :boolean;      
DELETE_VEHICULE_DEPASSANT:boolean;     
DETAILS_VEHICULE_DEPASSANT :boolean; 
//Ordre de mission


  VIEW_SOUS_FAMILLES_ARTICLES: boolean;
  ADD_SOUS_FAMILLES_ARTICLES: boolean;
  MODIFY_SOUS_FAMILLES_ARTICLES: boolean;
  DELETE_SOUS_FAMILLES_ARTICLES: boolean;
  VIEW_FAMILLES_ARTICLES: boolean;
  ADD_FAMILLES_ARTICLES: boolean;
  MODIFY_FAMILLES_ARTICLES: boolean;
  DELETE_FAMILLES_ARTICLES: boolean;
  VIEW_ALERTES: boolean;
  ADD_ALERTES: boolean;
  MODIFY_ALERTES: boolean;
  DELETE_ALERTES: boolean;
  VIEW_USERS: boolean;
  ADD_USERS: boolean;
  MODIFY_USERS: boolean;
  DELETE_USERS: boolean;
  VIEW_MESSAGES_APPLICATIFS: boolean;
  ADD_MESSAGES_APPLICATIFS: boolean;
  MODIFY_MESSAGES_APPLICATIFS: boolean;
  DELETE_MESSAGES_APPLICATIFS: boolean;
  VIEW_TRACABILITES: boolean;
  DELETE_TRACABILITES: boolean;
  VIEW_PARAMETRES_APPLICATION: boolean;
  ADD_PARAMETRES_APPLICATION: boolean;
  ACTIVATE_USERS: boolean;
  LOCK_USERS: boolean;
  MODIFY_PASSWORD_USERS: boolean;
  RESET_PASSWORD_USERS: boolean;
  VIEW_CAUSES_SINISTRES: boolean;
  ADD_CAUSES_SINISTRES: boolean;
  MODIFY_CAUSES_SINISTRES: boolean;
  DELETE_CAUSES_SINISTRES: boolean;
  VIEW_USAGES_VEHICULES: boolean;
  ADD_USAGES_VEHICULES: boolean;
  MODIFY_USAGES_VEHICULES: boolean;
  DELETE_USAGES_VEHICULES: boolean;
  VIEW_GROUPES_USERS: boolean;
  ADD_GROUPES_USERS: boolean;
  MODIFY_GROUPES_USERS: boolean;
  DELETE_GROUPES_USERS: boolean;
  VIEW_GPS: boolean;
  ADD_GPS: boolean;
  MODIFY_GPS: boolean;
  DELETE_GPS: boolean;
  MODIFY_PARAMETRES_APPLICATION: boolean;
  VIEW_VEHICULE: boolean;
  ADD_VEHICULE: boolean;
  MODIFY_VEHICULE: boolean;
  DELETE_VEHICULE: boolean;
  VIEW_TAXE_CIRCULATION: boolean;
  ADD_TAXE_CIRCULATION: boolean;
  MODIFY_TAXE_CIRCULATION: boolean;
  DELETE_TAXE_CIRCULATION: boolean;
  VIEW_ASSURANCE: boolean;
  ADD_ASSURANCE: boolean;
  MODIFY_ASSURANCE: boolean;
  DELETE_ASSURANCE: boolean;
  VIEW_VISITE_TECHNIQUE: boolean;
  ADD_VISITE_TECHNIQUE: boolean;
  MODIFY_VISITE_TECHNIQUE: boolean;
  DELETE_VISITE_TECHNIQUE: boolean;
  VIEW_REFORME: boolean;
  ADD_REFORME: boolean;
  MODIFY_REFORME: boolean;
  DELETE_REFORME: boolean;
  MODIFY_BONCOMMANDE: boolean;
  DELETE_BONCOMMANDE: boolean;
  VIEW_BONCOMMANDE:boolean;
  ADD_BONCOMMANDE:boolean;                
  MODIFY_BON_COMMANDE: boolean;
  DELETE_BON_COMMANDE: boolean;
  VIEW_BON_COMMANDE:boolean;
  ADD_BON_COMMANDE:boolean;       
  VIEW_DEMANDE_AFFECTATION:boolean;
  MODIFY_DEMANDE_AFFECTATION:boolean;
  DELETE_DEMANDE_AFFECTATION:boolean;
  ADD_DEMANDE_AFFECTATION:boolean;
  VIEW_DEMANDE_DESAFECTAION:boolean;
  MODIFY_DEMANDE_DESAFECTATION:boolean;
  DELETE_DEMANDE_DESAFECTATION:boolean;
  VIEW_DECLARATION_PERTE:boolean;
  ADD_DECLARATION_PERTE:boolean;
  DELETE_DECLARATION_PERTE:boolean;
  MODIFY_DECLARATION_PERTE:boolean;
  VIEW_HISTORIQUE_DECLARATION_PERTE:boolean;
  DELETE_HISTORIQUE_DECLARATION_PERTE:boolean;
  VIEW_DEMANDE_QUOTA:boolean;
  MODIFY_DEMANDE_QUOTA:boolean;
  DELETE_DEMANDE_QUOTA:boolean;
  ADD_DEMANDE_QUOTA:boolean;

  
  VIEW_AGILIS_CASH:boolean;
  ADD_AGILIS_CASH:boolean;
  MODIFY_AGILIS_CASH:boolean;
  DELETE_AGILIS_CASH:boolean;
  VEHICULE_AGILIS_CASH:boolean;

  VIEW_RECHARGE_AGILIS:boolean;
  ADD_RECHARGE_AGILIS:boolean;
  MODIFY_RECHARGE_AGILIS:boolean;
  DELETE_RECHARGE_AGILIS:boolean;
  VEHICULE_RECHARGE_AGILIS:boolean;
  CONFIRMER_RECHARGE_AGILIS:boolean;
  VALIDER_RECHARGE_AGILIS:boolean;

  VIEW_DECLARATION_PERTE_AGILIS:boolean;
  DELETE_DECLARATION_PERTE_AGILIS:boolean;
  MODIFY_DECLARATION_PERTE_AGILIS:boolean;
  ADD_DECLARATION_PERTE_AGILIS:boolean;
  CONFIRMER_DECLARATION_PERTE_AGILIS:boolean;

  VIEW_HISTORIQUE_PERTE_AGILIS:boolean;
  DELETE_HISTORIQUE_PERTE_AGILIS:boolean;

  VIEW_ANNULATION_AGILIS:boolean;
  ADD_ANNULATION_AGILIS:boolean;
  MODIFY_ANNULATION_AGILIS:boolean;
  DELETE_ANNULATION_AGILIS:boolean;
 //REFERENTIEL
 VIEW_ARTICLES: boolean;
 ADD_ARTICLES: boolean;
 MODIFY_ARTICLES: boolean;
 DELETE_ARTICLES: boolean;
 VIEW_GOUVERNORATS: boolean;
 ADD_GOUVERNORATS: boolean;
 MODIFY_GOUVERNORATS: boolean;
 DELETE_GOUVERNORATS: boolean;
 VIEW_STATIONS_PEAGE: boolean;
 ADD_STATIONS_PEAGE: boolean;
 MODIFY_STATIONS_PEAGE: boolean;
 DELETE_STATIONS_PEAGE: boolean;
 VIEW_EXPERTS: boolean;
 ADD_EXPERTS: boolean;
 MODIFY_EXPERTS: boolean;
 DELETE_EXPERTS: boolean;
 VIEW_FOURNISSEURS: boolean;
 ADD_FOURNISSEURS: boolean;
 MODIFY_FOURNISSEURS: boolean;
 DELETE_FOURNISSEURS: boolean;
 VIEW_LIEUX_PARKING: boolean;
 ADD_LIEUX_PARKING: boolean;
 MODIFY_LIEUX_PARKING: boolean;
 DELETE_LIEUX_PARKING: boolean;
 VIEW_FAMILLES_OPERATIONS_REPARATION: boolean;
 ADD_FAMILLES_OPERATIONS_REPARATION: boolean;
 MODIFY_FAMILLES_OPERATIONS_REPARATION: boolean;
 DELETE_FAMILLES_OPERATIONS_REPARATION: boolean;
 VIEW_OPERATIONS_REPARATION: boolean;
 ADD_OPERATIONS_REPARATION: boolean;
 MODIFY_OPERATIONS_REPARATION: boolean;
 DELETE_OPERATIONS_REPARATION: boolean;
 VIEW_PROGRAMMES_ENTRETIENS_PREVENTIFS: boolean;
 ADD_PROGRAMMES_ENTRETIENS_PREVENTIFS: boolean;
 MODIFY_PROGRAMMES_ENTRETIENS_PREVENTIFS: boolean;
 DELETE_PROGRAMMES_ENTRETIENS_PREVENTIFS: boolean;
 VIEW_ANNEES: boolean;
 ADD_ANNEES: boolean;
 DELETE_ANNEES: boolean;
 VIEW_ENERGIES: boolean;
 ADD_ENERGIES: boolean;
 MODIFY_ENERGIES: boolean;
 DELETE_ENERGIES: boolean;
 VIEW_TVA: boolean;
 ADD_TVA: boolean;
 MODIFY_TVA: boolean;
 DELETE_TVA: boolean;
 VIEW_UNITES: boolean;
 ADD_UNITES: boolean;
 DELETE_UNITES: boolean;
 VIEW_GENRES_VEHICULE: boolean;
 ADD_GENRES_VEHICULE: boolean;
 MODIFY_GENRES_VEHICULE: boolean;
 DELETE_GENRES_VEHICULE: boolean;
 VIEW_MARQUES_VEHICULE: boolean;
 ADD_MARQUES_VEHICULE: boolean;
 MODIFY_MARQUES_VEHICULE: boolean;
 DELETE_MARQUES_VEHICULE: boolean;
 VIEW_TYPES_VEHICULE: boolean;
 ADD_TYPES_VEHICULE: boolean;
 MODIFY_TYPES_VEHICULE: boolean;
 DELETE_TYPES_VEHICULE: boolean;
 VIEW_STRUCTURE_ADMINISTRATIVE: boolean;
 ADD_STRUCTURE_ADMINISTRATIVE: boolean;
 MODIFY_STRUCTURE_ADMINISTRATIVE: boolean;
 DELETE_STRUCTURE_ADMINISTRATIVE: boolean;
 VIEW_UNITE_GESTION_PARC: boolean;
 ADD_UNITE_GESTION_PARC: boolean;
 MODIFY_UNITE_GESTION_PARC: boolean;
 DELETE_UNITE_GESTION_PARC: boolean;
 VIEW_DETAILS_PERSONNELS: boolean;
 ADD_DETAILS_PERSONNELS: boolean;
 MODIFY_DETAILS_PERSONNELS: boolean;
 DELETE_DETAILS_PERSONNELS: boolean;
 VIEW_ETATS_STOCK: boolean;
 ADD_ETATS_STOCK: boolean;
 MODIFY_ETATS_STOCK: boolean;
 DELETE_ETATS_STOCK: boolean;
 VIEW_BENEFICIAIRES_EMPRUNTS: boolean;
 ADD_BENEFICIAIRES_EMPRUNTS: boolean;
 MODIFY_BENEFICIAIRES_EMPRUNTS: boolean;
 DELETE_BENEFICIAIRES_EMPRUNTS: boolean;
 //REFERENTIEL
 
  //EXPLOITATION 
  VIEW_RESERVATION:boolean;
  ADD_RESERVATION:boolean;
  MODIFY_RESERVATION:boolean;
  DELETE_RESERVATION:boolean;
  VIEW_VEHICULE_RESERVATION:boolean;
  CONFIRMER_RESERVATION:boolean;
  VIEW_LOCATION:boolean;
  ADD_LOCATION:boolean;
  MODIFY_LOCATION:boolean;
  DELETE_LOCATION:boolean;
  VIEW_SINISTRE:boolean;
  ADD_SINISTRE:boolean;
  MODIFY_SINISTRE:boolean;
  DELETE_SINISTRE:boolean;
  VIEW_VEHICULE_SINISTRE:boolean;
  VIEW_EMPRUNT:boolean;
  ADD_EMPRUNT:boolean;
  MODIFY_EMPRUNT:boolean;
  DELETE_EMPRUNT:boolean;
  VIEW_VEHICULE_EMPRUNT:boolean;
  CONFIRMER_EMPRUNT:boolean;
  //EXPLOITATION

  //CARBURANT : CARTE PLAFOND

VIEW_CARTE_PLAFOND:boolean;
MODIFY_CARTE_PLAFOND:boolean;
DELETE_CARTE_PLAFOND:boolean;
ADD_CARTE_PLAFOND:boolean;
CONFIRMER_ANNULATION_AGILIS :boolean;

VIEW_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
DELETE_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
ADD_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
CONFIRM_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
VALIDATION_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
VEHICULE_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
VIEW_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
DELETE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;
VEHICULE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:boolean;

VIEW_DECLARATION_PERTE_CARTE_PLAFOND:boolean;
MODIFY_DECLARATION_PERTE_CARTE_PLAFOND:boolean;
DELETE_DECLARATION_PERTE_CARTE_PLAFOND:boolean;
ADD_DECLARATION_PERTE_CARTE_PLAFOND:boolean;
CONFIRMATION_DECLARATION_PERTE_CARTE_PLAFOND:boolean;

VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND:boolean;
DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND:boolean;

ADD_DEMANDE_ANNULATION_CARTE_PLAFOND:boolean;

VIEW_DEMANDE_ANNULATION_CARTE_PLAFOND:boolean;
MODIFY_DEMANDE_ANNULATION_CARTE_PLAFOND:boolean;
DELETE_DEMANDE_ANNULATION_CARTE_PLAFOND:boolean;
CONFIRMATION_DEMANDE_ANNULATION_CARTE_PLAFOND:boolean;

VIEW_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND:boolean;
DELETE_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND:boolean;

//CARBURANT : CARTE PLAFOND

//STOCK

DELETE_TRANSFERT_PARC_VERS_MAGASIN:boolean;
MODIFY_TRANSFERT_PARC_VERS_MAGASIN:boolean;
CONFIRM_TRANSFERT_PARC_VERS_MAGASIN:boolean;
VALID_TRANSFERT_PARC_VERS_MAGASIN: boolean;
ADD_TRANSFERT_PARC_VERS_MAGASIN: boolean;
VIEW_TRANSFERT_PARC_VERS_MAGASIN: boolean;

VIEW_Bon_Travail_Sortie:boolean;
DETAILS_Bon_Travail_Sortie:boolean;
VIEW_Bon_Transfert_vers_magasin:boolean;
CONFIRM_Bon_Transfert_vers_magasin :boolean;
VALIDER_Bon_Transfert_vers_magasin :boolean;
MODIFY_Bon_Transfert_vers_magasin :boolean;
DELETE_Bon_Transfert_vers_magasin :boolean;
ADD_Bon_Transfert_vers_magasin :boolean;
VIEW_Bon_Sortie_Structure :boolean;
VIEW_Reception_Fournisseur:boolean;
DELETE_Reception_Fournisseur :boolean;
DETAILS_Reception_Fournisseur:boolean;
VIEW_Reception_Atelier:boolean;

VIEW_Transfert_magasin:boolean;
VIEW_Retour_Structure:boolean;
DETAILS_Retour_Structure:boolean;
DELETE_Retour_Structure:boolean;
ADD_Retour_Structure:boolean;
VIEW_Inventaire_Stock:boolean;
DETAILS_Inventaire_Stock :boolean;
DELETE_Inventaire_Stock:boolean;
ADD_Inventaire_Stock:boolean;

VIEW_Regulation_Stock:boolean;
DETAILS_Regulation_Stock:boolean;
DELETE_Regulation_Stock:boolean;
ADD_Regulation_Stock:boolean;
//STOCK


//CARBURANT : CARTE JOCKER

VIEW_CARTE_JOCKER:boolean;
MODIFY_CARTE_JOCKER:boolean;
DELETE_CARTE_JOCKER:boolean;
ADD_CARTE_JOCKER:boolean;


CONFIRMATION_DEMANDE_AFFECTATION_CARTE_JOCKER: boolean;
VALIDATION_DEMANDE_AFFECTATION_CARTE_JOCKER: boolean;
VIEW_DEMANDE_AFFECTATION_CARTE_JOCKER: boolean;
MODIFY_DEMANDE_AFFECTATION_CARTE_JOCKER: boolean;
ADD_DEMANDE_AFFECTATION_CARTE_JOCKER: boolean;
VEHICULE_DEMANDE_AFFECTATION_CARTE_JOCKER: boolean;
DELETE_DEMANDE_AFFECTATION_CARTE_JOCKER: boolean;


CONFIRMATION_DEMANDE_DESAFFECTATION_CARTE_JOCKER: boolean;
VIEW_DEMANDE_DESAFFECTATION_CARTE_JOCKER: boolean;
MODIFY_DEMANDE_DESAFFECTATION_CARTE_JOCKER: boolean;
DELETE_DEMANDE_DESAFFECTATION_CARTE_JOCKER: boolean;
ADD_DEMANDE_DESAFFECTATION_CARTE_JOCKER: boolean;


ADD_DECLARATION_PERTE_CARTE_JOCKER: boolean;
DELETE_DECLARATION_PERTE_CARTE_JOCKER: boolean;
MODIFY_DECLARATION_PERTE_CARTE_JOCKER: boolean;
CONFIRMATION_DECLARATION_PERTE_CARTE_JOCKER: boolean;
VIEW_DECLARATION_PERTE_CARTE_JOCKER: boolean;

VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER: boolean;
DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER: boolean;



CONFIRMATION_DEMANDE_QUOTA_CARTE_JOCKER: boolean;
VALIDATION_DEMANDE_QUOTA_CARTE_JOCKER: boolean;
ADD_DEMANDE_QUOTA_CARTE_JOCKER: boolean;
MODIFY_DEMANDE_QUOTA_CARTE_JOCKER: boolean;
DELETE_DEMANDE_QUOTA_CARTE_JOCKER: boolean;
VIEW_DEMANDE_QUOTA_CARTE_JOCKER: boolean;
//CARBURANT : CARTE JOCKER

//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 
CONFIRMATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: boolean;
VALIDATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: boolean;
ADD_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: boolean;
MODIFY_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: boolean;
DELETE_RECHARGE_CARBURANT_COMPENSATION: boolean;
VIEW_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: boolean;
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 

//CARBURANT : RECHARGE_QUOTA_MENSUEL 
CONFIRM_RECHARGE_QUOTA_MENSUEL:boolean;
VALID_RECHARGE_QUOTA_MENSUEL: boolean;
ADD_RECHARGE_QUOTA_MENSUEL: boolean;
VIEW_RECHARGE_QUOTA_MENSUEL: boolean;
//CARBURANT :RECHARGE_QUOTA_MENSUEL

//CARBURANT : HISTORIUE RECHARGE_QUOTA_MENSUEL 
VIEW_HISTORIQUE_RECHARGE_QUOTA_MENSUEL: boolean;
//CARBURANT :RECHARGE_QUOTA_MENSUEL



MODIFY_DEMANDE_INTERVENTION: boolean;
 DELETE_DEMANDE_INTERVENTION: boolean;
 VIEW_DEMANDE_INTERVENTION: boolean;
 ADD_DEMANDE_INTERVENTION: boolean;

 DETAILS_BON_TRAVAIL: boolean;
 DELETE_BON_TRAVAIL: boolean;
 VIEW_BON_TRAVAIL: boolean;
 ADD_BON_TRAVAIL: boolean;
 MODIFY_SORTIE_VEHICULE: boolean;
 VIEW_SORTIE_VEHICULE: boolean;
//End Maintenance
// CARBURANT : Distribution de carburant
MODIFY_DISTRIBUTION_CARBURANT_FONCTION: boolean;
DELETE_DISTRIBUTION_CARBURANT_FONCTION: boolean;
VIEW_DISTRIBUTION_CARBURANT_FONCTION: boolean;
VEHICULE_DISTRIBUTION_CARBURANT_FONCTION: boolean;
ADD_DISTRIBUTION_CARBURANT_FONCTION: boolean;

ADD_DISTRIBUTION_CARBURANT_VEHICULE: boolean;
MODIFY_DISTRIBUTION_CARBURANT_VEHICULE: boolean;
DELETE_DISTRIBUTION_CARBURANT_VEHICULE: boolean;
VIEW_DISTRIBUTION_CARBURANT_VEHICULE: boolean;

ADD_DESTRIBUTION_CARBURANT_SERVICE: boolean;
MODIFY_DESTRIBUTION_CARBURANT_SERVICE: boolean;
DELETE_DESTRIBUTION_CARBURANT_SERVICE: boolean;
VIEW_DESTRIBUTION_CARBURANT_SERVICE: boolean;
VEHICULE_DESTRIBUTION_CARBURANT_SERVICE: boolean;

ADD_DESTRIBUTION_CARBURANT_COMPENSATION: boolean;
MODIFY_DESTRIBUTION_CARBURANT_COMPENSATION: boolean;
DELETE_DESTRIBUTION_CARBURANT_COMPENSATION: boolean;
VIEW_DESTRIBUTION_CARBURANT_COMPENSATION: boolean;
VEHICULE_DESTRIBUTION_CARBURANT_COMPENSATION: boolean;

ADD_TRANSFERT_PARC: boolean;
VIEW_TRANSFERT_PARC: boolean;
DETAIL_TRANSFERT_PARC: boolean;

ADD_RETOUR_CARBURANT: boolean;
VIEW_RETOUR_CARBURANT: boolean;

ADD_ETAT_MENSUEL: boolean;
MODIFY_ETAT_MENSUEL: boolean;
DELETE_ETAT_MENSUEL: boolean;
VIEW_ETAT_MENSUEL: boolean;
VEHICULE_ETAT_MENSUEL: boolean;
VALIDER_ETAT_MENSUEL: boolean;
CONFIRMER_ETAT_MENSUEL: boolean;

ADD_BON_CARBURANT_BON: boolean;
VIEW_BON_CARBURANT_BON: boolean;

ADD_SUIVI: boolean;
VIEW_SUIVI: boolean;

VIEW_DEMANDE_RECHARGE_SOUS_COMPTE : boolean;
ADD_DEMANDE_RECHARGE_SOUS_COMPTE : boolean;
VALID_DEMANDE_RECHARGE_SOUS_COMPTE : boolean;
CONFIRM_DEMANDE_RECHARGE_SOUS_COMPTE : boolean;
DELETE_DEMANDE_RECHARGE_SOUS_COMPTE: boolean;





//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 
CONFIRMATION_DEMANDE_RECHARGE_COMPLEMENTAIRE: boolean;
VALIDATION_DEMANDE_RECHARGE_COMPLEMENTAIRE: boolean;
ADD_DEMANDE_RECHARGE_COMPLEMENTAIRE: boolean;
MODIFY_DEMANDE_RECHARGE_COMPLEMENTAIRE: boolean;
DELETE_RECHARGE_COMPLEMENTAIRE: boolean;
VIEW_DEMANDE_RECHARGE_COMPLEMENTAIRE: boolean;
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 



// CARBURANT : Distribution de 

VIEW_HISTORIQUE_MAINTENANCE: boolean;
DELETE_HISTORIQUE_MAINTENANCE: boolean;


VIEW_HISTORIQUE_REGULATION: boolean;
DELETE_HISTORIQUE_REGULATION: boolean;

VIEW_HISTORIQUE_MAINTENANCE_VEHICULE: boolean;
DELETE_HISTORIQUE_MAINTENANCE_VEHICULE: boolean;

VIEW_ALERT_VEHICULE : boolean;
VIEW_ALERT_STOCK : boolean;


RECU_DEMANDE_INTERVENTION:boolean;
VEHICULE_DEMANDE_INTERVENTION:boolean;
ANNULATION_DEMANDE_INTERVENTION:boolean;
REOUVRIR_SORTIE_VEHICULE:boolean;
}

