import {Injectable, OnInit} from '@angular/core';
import {HttpClient, HttpResponse} from '@angular/common/http';
import {Utilisateur} from './home-page/administration/creation-utilisateurs/utilisateur';
import {Observable} from 'rxjs';
import {JwtHelperService} from '@auth0/angular-jwt';
import {environment} from '../../environments/environment.prod';
import {AuthoritiesUtilisateur} from './authorities-utilisateur';
import {CustomUser} from './home-page/custom-user';
import {Router} from '@angular/router';
import {Structure} from './home-page/referentiel/specifique/structure-administrative/structure';
import {ReferentielSpecifiqueServiceService} from './home-page/referentiel/specifique/referentiel-specifique-service.service';
import * as CryptoJS from 'crypto-js';
import { ConfirmationDeclarationPerteCarteComponent } from './home-page/carburant/carte-plafond/gestion-declaration-perte-carte/confirmation-declaration-perte-carte/confirmation-declaration-perte-carte.component';
import { HomePageComponent } from './home-page/home-page.component';


interface CurrentUser {
  matricule: string;
  mot2passe: string;
}
@Injectable({
  providedIn: 'root'
})
export class AuthenticationServiceService  {
  currentUser: CurrentUser = {
    matricule: '',
    mot2passe: '',
  };
  serverURL = environment.serverUrl;
  authoritiesUtilisateur: AuthoritiesUtilisateur = {


    RECU_DEMANDE_INTERVENTION:false,
    VEHICULE_DEMANDE_INTERVENTION:false,
    ANNULATION_DEMANDE_INTERVENTION:false,
    REOUVRIR_SORTIE_VEHICULE:false,
    DELETE_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE : false,
    VIEW_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE  : false,
    ADD_SOUS_FAMILLES_ARTICLES: false,
    DELETE_SOUS_FAMILLES_ARTICLES: false,
    MODIFY_SOUS_FAMILLES_ARTICLES: false,
    VIEW_SOUS_FAMILLES_ARTICLES: false,
    VIEW_FAMILLES_ARTICLES: false,
    ADD_FAMILLES_ARTICLES: false,
    MODIFY_FAMILLES_ARTICLES: false,
    DELETE_FAMILLES_ARTICLES: false,
    CONFIRMER_ANNULATION_AGILIS :false,

    VIEW_ALERTES: false,
    ADD_ALERTES: false,
    MODIFY_ALERTES: false,
    DELETE_ALERTES: false,
    VIEW_USERS: false,
    ADD_USERS: false,
    MODIFY_USERS: false,
    DELETE_USERS: false,
    VIEW_MESSAGES_APPLICATIFS: false,
    ADD_MESSAGES_APPLICATIFS: false,
    MODIFY_MESSAGES_APPLICATIFS: false,
    DELETE_MESSAGES_APPLICATIFS: false,
    VIEW_TRACABILITES: false,
    DELETE_TRACABILITES: false,
    VIEW_PARAMETRES_APPLICATION: false,
    ADD_PARAMETRES_APPLICATION: false,
    ACTIVATE_USERS: false,
    LOCK_USERS: false,
    MODIFY_PASSWORD_USERS: false,
    RESET_PASSWORD_USERS: false,
    VIEW_CAUSES_SINISTRES: false,
    ADD_CAUSES_SINISTRES: false,
    MODIFY_CAUSES_SINISTRES: false,
    DELETE_CAUSES_SINISTRES: false,
    VIEW_USAGES_VEHICULES: false,
    ADD_USAGES_VEHICULES: false,
    MODIFY_USAGES_VEHICULES: false,
    DELETE_USAGES_VEHICULES: false,
    VIEW_GROUPES_USERS: false,
    ADD_GROUPES_USERS: false,
    MODIFY_GROUPES_USERS: false,
    DELETE_GROUPES_USERS: false,
    VIEW_GPS: false,
    ADD_GPS: false,
    MODIFY_GPS: false,
    DELETE_GPS: false,
    MODIFY_PARAMETRES_APPLICATION: false,
    VIEW_VEHICULE: false,
    ADD_VEHICULE: false,
    MODIFY_VEHICULE: false,
    DELETE_VEHICULE: false,
    VIEW_TAXE_CIRCULATION: false,
    ADD_TAXE_CIRCULATION: false,
    MODIFY_TAXE_CIRCULATION: false,
    DELETE_TAXE_CIRCULATION: false,
    VIEW_ASSURANCE: false,
    ADD_ASSURANCE: false,
    MODIFY_ASSURANCE: false,
    DELETE_ASSURANCE: false,
    VIEW_VISITE_TECHNIQUE: false,
    ADD_VISITE_TECHNIQUE: false,
    MODIFY_VISITE_TECHNIQUE: false,
    DELETE_VISITE_TECHNIQUE: false,
    VIEW_REFORME: false,
    ADD_REFORME: false,
    MODIFY_REFORME: false,
    DELETE_REFORME: false,
    VIEW_BONCOMMANDE:false,
    ADD_BONCOMMANDE:false,
    MODIFY_BONCOMMANDE:false,
    DELETE_BONCOMMANDE:false,
  VIEW_DEMANDE_AFFECTATION:false,
  MODIFY_DEMANDE_AFFECTATION:false,
  DELETE_DEMANDE_AFFECTATION:false,
  ADD_DEMANDE_AFFECTATION:false,
  VIEW_DEMANDE_DESAFECTAION:false,
  MODIFY_DEMANDE_DESAFECTATION:false,
  DELETE_DEMANDE_DESAFECTATION:false,
  VIEW_DECLARATION_PERTE:false,
  ADD_DECLARATION_PERTE:false,
  DELETE_DECLARATION_PERTE:false,
  MODIFY_DECLARATION_PERTE:false,
  VIEW_HISTORIQUE_DECLARATION_PERTE:false,
  DELETE_HISTORIQUE_DECLARATION_PERTE:false,
  VIEW_DEMANDE_QUOTA:false,
  MODIFY_DEMANDE_QUOTA:false,
  DELETE_DEMANDE_QUOTA:false,
  ADD_DEMANDE_QUOTA:false,

  VIEW_AGILIS_CASH:false,
  ADD_AGILIS_CASH:false,
  MODIFY_AGILIS_CASH:false,
  DELETE_AGILIS_CASH:false,
  VEHICULE_AGILIS_CASH:false,

  VIEW_RECHARGE_AGILIS:false,
  ADD_RECHARGE_AGILIS:false,
  MODIFY_RECHARGE_AGILIS:false,
  DELETE_RECHARGE_AGILIS:false,
  VEHICULE_RECHARGE_AGILIS:false,
  CONFIRMER_RECHARGE_AGILIS:false,
  VALIDER_RECHARGE_AGILIS:false,

  VIEW_DECLARATION_PERTE_AGILIS:false,
  DELETE_DECLARATION_PERTE_AGILIS:false,
  MODIFY_DECLARATION_PERTE_AGILIS:false,
  ADD_DECLARATION_PERTE_AGILIS:false,
  CONFIRMER_DECLARATION_PERTE_AGILIS:false,

  VIEW_HISTORIQUE_PERTE_AGILIS:false,
  DELETE_HISTORIQUE_PERTE_AGILIS:false,

  VIEW_ANNULATION_AGILIS:false,
  ADD_ANNULATION_AGILIS:false,
  MODIFY_ANNULATION_AGILIS:false,
  DELETE_ANNULATION_AGILIS:false,


//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 
CONFIRMATION_DEMANDE_RECHARGE_COMPLEMENTAIRE:false,
VALIDATION_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
ADD_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
MODIFY_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
DELETE_RECHARGE_COMPLEMENTAIRE: false,
VIEW_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 

//CARBURANT : RECHARGE_QUOTA_MENSUEL 
CONFIRM_RECHARGE_QUOTA_MENSUEL:false,
VALID_RECHARGE_QUOTA_MENSUEL: false,
ADD_RECHARGE_QUOTA_MENSUEL: false,
VIEW_RECHARGE_QUOTA_MENSUEL: false,
//CARBURANT :RECHARGE_QUOTA_MENSUEL

//CARBURANT : historique RECHARGE_QUOTA_MENSUEL 
VIEW_HISTORIQUE_RECHARGE_QUOTA_MENSUEL: false,
//CARBURANT :RECHARGE_QUOTA_MENSUEL

//Ordre de mission
    VIEW_ORDRE_MISSION :false,
    ADD_ORDRE_MISSION:false,
    MODIFY_ORDRE_MISSION: false,
    DELETE_ORDRE_MISSION:false,
    VEHICULE_ORDRE_MISSION:false,
    CONFIRMER_ORDRE_MISSION:false,
    VEHICULE_VEHICULE_DEPASSANT:false,
    DELETE_VEHICULE_DEPASSANT:false,     
    DETAILS_VEHICULE_DEPASSANT :false, 
    VIEW_VEHICULE_DEPASSANT :false,
//Ordre de mission
//ACHAT
MODIFY_BON_COMMANDE: false,
DELETE_BON_COMMANDE: false,
VIEW_BON_COMMANDE:false,
ADD_BON_COMMANDE:false,
//ACHAT

//stock

DELETE_TRANSFERT_PARC_VERS_MAGASIN:false,
MODIFY_TRANSFERT_PARC_VERS_MAGASIN:false,
CONFIRM_TRANSFERT_PARC_VERS_MAGASIN:false,
VALID_TRANSFERT_PARC_VERS_MAGASIN: false,
ADD_TRANSFERT_PARC_VERS_MAGASIN: false,
VIEW_TRANSFERT_PARC_VERS_MAGASIN: false,


VIEW_Bon_Travail_Sortie:false,
DETAILS_Bon_Travail_Sortie:false,
VIEW_Bon_Transfert_vers_magasin:false,
CONFIRM_Bon_Transfert_vers_magasin :false,
ADD_Bon_Transfert_vers_magasin :false,
VALIDER_Bon_Transfert_vers_magasin :false,
MODIFY_Bon_Transfert_vers_magasin :false,
DELETE_Bon_Transfert_vers_magasin :false,
VIEW_Bon_Sortie_Structure :false,
VIEW_Reception_Fournisseur:false,
DELETE_Reception_Fournisseur :false,
DETAILS_Reception_Fournisseur:false,
VIEW_Reception_Atelier:false,
VIEW_Transfert_magasin:false,
VIEW_Retour_Structure:false,
DETAILS_Retour_Structure:false,
DELETE_Retour_Structure:false,
ADD_Retour_Structure:false,
VIEW_Inventaire_Stock:false,
DETAILS_Inventaire_Stock :false,
DELETE_Inventaire_Stock:false,
ADD_Inventaire_Stock:false,
VIEW_Regulation_Stock:false,
DETAILS_Regulation_Stock:false,
DELETE_Regulation_Stock:false,
ADD_Regulation_Stock:false,

VIEW_HISTORIQUE_REGULATION:false,
DELETE_HISTORIQUE_REGULATION:false,
//stock


 //REFERENTIEL
 VIEW_ARTICLES: false,
 ADD_ARTICLES: false,
 MODIFY_ARTICLES: false,
 DELETE_ARTICLES: false,
 VIEW_GOUVERNORATS: false,
 ADD_GOUVERNORATS: false,
 MODIFY_GOUVERNORATS: false,
 DELETE_GOUVERNORATS: false,
 VIEW_STATIONS_PEAGE: false,
 ADD_STATIONS_PEAGE: false,
 MODIFY_STATIONS_PEAGE: false,
 DELETE_STATIONS_PEAGE: false,
 VIEW_EXPERTS: false,
 ADD_EXPERTS: false,
 MODIFY_EXPERTS: false,
 DELETE_EXPERTS: false,
 VIEW_FOURNISSEURS: false,
 ADD_FOURNISSEURS: false,
 MODIFY_FOURNISSEURS: false,
 DELETE_FOURNISSEURS: false,
 VIEW_LIEUX_PARKING: false,
 ADD_LIEUX_PARKING: false,
 MODIFY_LIEUX_PARKING: false,
 DELETE_LIEUX_PARKING: false,
 VIEW_FAMILLES_OPERATIONS_REPARATION: false,
 ADD_FAMILLES_OPERATIONS_REPARATION: false,
 MODIFY_FAMILLES_OPERATIONS_REPARATION: false,
 DELETE_FAMILLES_OPERATIONS_REPARATION: false,
 VIEW_OPERATIONS_REPARATION: false,
 ADD_OPERATIONS_REPARATION: false,
 MODIFY_OPERATIONS_REPARATION: false,
 DELETE_OPERATIONS_REPARATION: false,
 VIEW_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
 ADD_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
 MODIFY_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
 DELETE_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
 VIEW_ANNEES: false,
 ADD_ANNEES: false,
 DELETE_ANNEES: false,
 VIEW_ENERGIES: false,
 ADD_ENERGIES: false,
 MODIFY_ENERGIES: false,
 DELETE_ENERGIES: false,
 VIEW_TVA: false,
 ADD_TVA: false,
 MODIFY_TVA: false,
 DELETE_TVA: false,
 VIEW_UNITES: false,
 ADD_UNITES: false,
 DELETE_UNITES: false,
 VIEW_GENRES_VEHICULE: false,
 ADD_GENRES_VEHICULE: false,
 MODIFY_GENRES_VEHICULE: false,
 DELETE_GENRES_VEHICULE: false,
 VIEW_MARQUES_VEHICULE: false,
 ADD_MARQUES_VEHICULE: false,
 MODIFY_MARQUES_VEHICULE: false,
 DELETE_MARQUES_VEHICULE: false,
 VIEW_TYPES_VEHICULE: false,
 ADD_TYPES_VEHICULE: false,
 MODIFY_TYPES_VEHICULE: false,
 DELETE_TYPES_VEHICULE: false,
 VIEW_STRUCTURE_ADMINISTRATIVE: false,
 ADD_STRUCTURE_ADMINISTRATIVE: false,
 MODIFY_STRUCTURE_ADMINISTRATIVE: false,
 DELETE_STRUCTURE_ADMINISTRATIVE: false,
 VIEW_UNITE_GESTION_PARC: false,
 ADD_UNITE_GESTION_PARC: false,
 MODIFY_UNITE_GESTION_PARC: false,
 DELETE_UNITE_GESTION_PARC: false,
 VIEW_DETAILS_PERSONNELS: false,
 ADD_DETAILS_PERSONNELS: false,
 MODIFY_DETAILS_PERSONNELS: false,
 DELETE_DETAILS_PERSONNELS: false,
 VIEW_ETATS_STOCK: false,
 ADD_ETATS_STOCK: false,
 MODIFY_ETATS_STOCK: false,
 DELETE_ETATS_STOCK: false,
 VIEW_BENEFICIAIRES_EMPRUNTS: false,
 ADD_BENEFICIAIRES_EMPRUNTS: false,
 MODIFY_BENEFICIAIRES_EMPRUNTS: false,
 DELETE_BENEFICIAIRES_EMPRUNTS: false,
 //REFERENTIEL
 

//EXPLOITATION
VIEW_RESERVATION:false,
ADD_RESERVATION:false,
MODIFY_RESERVATION:false,
DELETE_RESERVATION:false,
VIEW_VEHICULE_RESERVATION:false,
CONFIRMER_RESERVATION:false,
VIEW_LOCATION:false,
ADD_LOCATION:false,
MODIFY_LOCATION:false,
DELETE_LOCATION:false,
VIEW_SINISTRE:false,
ADD_SINISTRE:false,
MODIFY_SINISTRE:false,
DELETE_SINISTRE:false,
VIEW_VEHICULE_SINISTRE:false,
VIEW_EMPRUNT:false,
ADD_EMPRUNT:false,
MODIFY_EMPRUNT:false,
DELETE_EMPRUNT:false,
VIEW_VEHICULE_EMPRUNT:false,
CONFIRMER_EMPRUNT:false,
//EXPLOITATION

 //CARBURANT : CARTE PLAFOND

 VIEW_CARTE_PLAFOND:false,
 MODIFY_CARTE_PLAFOND:false,
 DELETE_CARTE_PLAFOND:false,
 ADD_CARTE_PLAFOND:false,
 
 VIEW_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 DELETE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 ADD_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 CONFIRM_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 VALIDATION_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 VEHICULE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,

 VIEW_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 DELETE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 VEHICULE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 
 VIEW_DECLARATION_PERTE_CARTE_PLAFOND:false,
 MODIFY_DECLARATION_PERTE_CARTE_PLAFOND:false,
 DELETE_DECLARATION_PERTE_CARTE_PLAFOND:false,
 ADD_DECLARATION_PERTE_CARTE_PLAFOND:false,
 CONFIRMATION_DECLARATION_PERTE_CARTE_PLAFOND:false,
 
 VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND:false,
 DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND:false,
 
 ADD_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 
 VIEW_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 MODIFY_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 DELETE_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 CONFIRMATION_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 
 VIEW_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 DELETE_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 
 //CARBURANT : CARTE PLAFOND


 //CARBURANT : CARTE JOCKER

VIEW_CARTE_JOCKER:false,
MODIFY_CARTE_JOCKER:false,
DELETE_CARTE_JOCKER:false,
ADD_CARTE_JOCKER:false,

CONFIRMATION_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
VALIDATION_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
VIEW_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
MODIFY_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
ADD_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
VEHICULE_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
DELETE_DEMANDE_AFFECTATION_CARTE_JOCKER: false,


CONFIRMATION_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
VIEW_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
MODIFY_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
DELETE_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
ADD_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,

ADD_DECLARATION_PERTE_CARTE_JOCKER: false,
DELETE_DECLARATION_PERTE_CARTE_JOCKER: false,
MODIFY_DECLARATION_PERTE_CARTE_JOCKER: false,
CONFIRMATION_DECLARATION_PERTE_CARTE_JOCKER: false,
VIEW_DECLARATION_PERTE_CARTE_JOCKER: false,

VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER: false,
DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER: false,

CONFIRMATION_DEMANDE_QUOTA_CARTE_JOCKER: false,
VALIDATION_DEMANDE_QUOTA_CARTE_JOCKER: false,
ADD_DEMANDE_QUOTA_CARTE_JOCKER: false,
MODIFY_DEMANDE_QUOTA_CARTE_JOCKER: false,
DELETE_DEMANDE_QUOTA_CARTE_JOCKER: false,
VIEW_DEMANDE_QUOTA_CARTE_JOCKER: false,


//CARBURANT : CARTE JOCKER

//Maitenance:
MODIFY_DEMANDE_INTERVENTION:false,
 DELETE_DEMANDE_INTERVENTION:false,
 VIEW_DEMANDE_INTERVENTION:false,
 ADD_DEMANDE_INTERVENTION:false,

 DETAILS_BON_TRAVAIL: false,
 DELETE_BON_TRAVAIL: false,
 VIEW_BON_TRAVAIL:false,
 ADD_BON_TRAVAIL:false,
 MODIFY_SORTIE_VEHICULE: false,
 VIEW_SORTIE_VEHICULE:false,
 VIEW_HISTORIQUE_MAINTENANCE: false,
 DELETE_HISTORIQUE_MAINTENANCE:false,
// CARBURANT : Distribution de carburant
ADD_DISTRIBUTION_CARBURANT_FONCTION: false,
MODIFY_DISTRIBUTION_CARBURANT_FONCTION: false,
DELETE_DISTRIBUTION_CARBURANT_FONCTION: false,
VIEW_DISTRIBUTION_CARBURANT_FONCTION: false,
VEHICULE_DISTRIBUTION_CARBURANT_FONCTION: false,

ADD_DISTRIBUTION_CARBURANT_VEHICULE: false,
MODIFY_DISTRIBUTION_CARBURANT_VEHICULE: false,
DELETE_DISTRIBUTION_CARBURANT_VEHICULE: false,
VIEW_DISTRIBUTION_CARBURANT_VEHICULE: false,

ADD_DESTRIBUTION_CARBURANT_SERVICE: false,
MODIFY_DESTRIBUTION_CARBURANT_SERVICE: false,
DELETE_DESTRIBUTION_CARBURANT_SERVICE: false,
VIEW_DESTRIBUTION_CARBURANT_SERVICE: false,
VEHICULE_DESTRIBUTION_CARBURANT_SERVICE: false,

ADD_DESTRIBUTION_CARBURANT_COMPENSATION: false,
MODIFY_DESTRIBUTION_CARBURANT_COMPENSATION: false,
DELETE_DESTRIBUTION_CARBURANT_COMPENSATION: false,
VIEW_DESTRIBUTION_CARBURANT_COMPENSATION: false,
VEHICULE_DESTRIBUTION_CARBURANT_COMPENSATION: false,

ADD_TRANSFERT_PARC: false,
VIEW_TRANSFERT_PARC: false,
DETAIL_TRANSFERT_PARC: false,

ADD_RETOUR_CARBURANT: false,
VIEW_RETOUR_CARBURANT: false,

ADD_ETAT_MENSUEL: false,
MODIFY_ETAT_MENSUEL: false,
DELETE_ETAT_MENSUEL: false,
VIEW_ETAT_MENSUEL: false,
VEHICULE_ETAT_MENSUEL: false,
VALIDER_ETAT_MENSUEL: false,
CONFIRMER_ETAT_MENSUEL: false,

ADD_BON_CARBURANT_BON: false,
VIEW_BON_CARBURANT_BON: false,

ADD_SUIVI: false,
VIEW_SUIVI: false,

VIEW_DEMANDE_RECHARGE_SOUS_COMPTE: false,
ADD_DEMANDE_RECHARGE_SOUS_COMPTE : false,
VALID_DEMANDE_RECHARGE_SOUS_COMPTE : false,
CONFIRM_DEMANDE_RECHARGE_SOUS_COMPTE : false,
DELETE_DEMANDE_RECHARGE_SOUS_COMPTE: false,

// CARBURANT : Distribution de carburant
VIEW_HISTORIQUE_MAINTENANCE_VEHICULE: false,
DELETE_HISTORIQUE_MAINTENANCE_VEHICULE: false,


//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 
CONFIRMATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION:false,
VALIDATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
ADD_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
MODIFY_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
DELETE_RECHARGE_CARBURANT_COMPENSATION: false,
VIEW_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 

VIEW_ALERT_VEHICULE : false,
VIEW_ALERT_STOCK : false,

  };
  private token: string;
  private loggedInUsername: string;
  private jwtHelper = new JwtHelperService();

  constructor(private  http: HttpClient, private router: Router, private ReferentielSpecifique: ReferentielSpecifiqueServiceService,
     ) {
  }
  public decryptedInfo;
  public encryptInfo;
  
  public login(utilisateur: Utilisateur): Observable<HttpResponse<CustomUser>> {
    return this.http.post<CustomUser>(this.serverURL + `/login`, utilisateur, {observe: 'response'});
  }

  public logOut(): void {
    this.token = null;
    localStorage.removeItem('user');
    localStorage.removeItem('token');
    this.router.navigate(['/login']);
  }

  public saveToken(token: string): void {
    this.token = token;
    localStorage.setItem('token', token);
  
  }

  public addUserToLocalCache(utilisateur: CustomUser): void {
    localStorage.setItem('user', JSON.stringify(utilisateur));
  }

  public getUserFromLocalCache(): Utilisateur {
    return JSON.parse(localStorage.getItem('user'));
  }

  public loadToken(): void {
    this.token = localStorage.getItem('token');
  }

  public loadUser(): CustomUser {
    return JSON.parse(localStorage.getItem('user'));
  }

  isSuperAdmin(): boolean {
    if (this.loadUser().structures.length === 0) {
      return true;
    } else {
      return false;
    }
  }

  getUserStrucutures(): Structure[] {
    let ListStructure: Structure[] = [];
    if (this.isSuperAdmin()) {
      this.ReferentielSpecifique.getListStructure().subscribe(value => {
        value.forEach(value1 => {
          ListStructure.push(value1);
        });
      });
    } else {
      ListStructure = this.loadUser().structures;
    }
    return ListStructure;
  }

  public getToken(): string {
    return this.token;
  }

  public getNomPrenom(): any {
    if (localStorage.getItem('user')) {
      const user: CustomUser = JSON.parse(localStorage.getItem('user'));
      return user.nom + ' ' + user.prenom;
    } else {
      return 'Utilisateur anonyme';
    }
  }

  public isAdministrator(): boolean {
    if (localStorage.getItem('user')) {
      const user: CustomUser = JSON.parse(localStorage.getItem('user'));
      if (user.typeCompte === 'Administrateur') {
        return true;
      } else {
        return false;
      }
    } else {
      return false;
    }
  }

  public isUserLoggedIn(): boolean {
    if (this.token != null || this.token != '') {
       if (!this.jwtHelper.isTokenExpired(this.token)) {
        this.loggedInUsername = this.jwtHelper.decodeToken(this.token).sub;
        return true;
      } 
      return true;
    } else {
      return false;
    }
  }

  getAuthoritiesUtilisateur(): AuthoritiesUtilisateur {
    return this.authoritiesUtilisateur;
  }

  setUserAuthorities(authorities: string[]) {
    this.authoritiesUtilisateur = {

      VIEW_ALERT_VEHICULE : false,
VIEW_ALERT_STOCK : false,

//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 
CONFIRMATION_DEMANDE_RECHARGE_COMPLEMENTAIRE:false,
VALIDATION_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
ADD_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
MODIFY_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
DELETE_RECHARGE_COMPLEMENTAIRE: false,
VIEW_DEMANDE_RECHARGE_COMPLEMENTAIRE: false,
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 


      
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 
CONFIRMATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION:false,
VALIDATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
ADD_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
MODIFY_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
DELETE_RECHARGE_CARBURANT_COMPENSATION: false,
VIEW_DEMANDE_RECHARGE_CARBURANT_COMPENSATION: false,
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 

//CARBURANT : RECHARGE_QUOTA_MENSUEL 
CONFIRM_RECHARGE_QUOTA_MENSUEL:false,
VALID_RECHARGE_QUOTA_MENSUEL: false,
ADD_RECHARGE_QUOTA_MENSUEL: false,
VIEW_RECHARGE_QUOTA_MENSUEL: false,
//CARBURANT :RECHARGE_QUOTA_MENSUEL

//CARBURANT : historique RECHARGE_QUOTA_MENSUEL 
VIEW_HISTORIQUE_RECHARGE_QUOTA_MENSUEL: false,
//CARBURANT :RECHARGE_QUOTA_MENSUEL


    DELETE_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE : false,
    VIEW_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE  : false,
//Maitenance:
MODIFY_DEMANDE_INTERVENTION:false,
 DELETE_DEMANDE_INTERVENTION:false,
 VIEW_DEMANDE_INTERVENTION:false,
 ADD_DEMANDE_INTERVENTION:false,
RECU_DEMANDE_INTERVENTION:false,
VEHICULE_DEMANDE_INTERVENTION:false,
ANNULATION_DEMANDE_INTERVENTION:false,
REOUVRIR_SORTIE_VEHICULE:false,

 DETAILS_BON_TRAVAIL: false,
 DELETE_BON_TRAVAIL: false,
 VIEW_BON_TRAVAIL:false,
 ADD_BON_TRAVAIL:false,

 MODIFY_SORTIE_VEHICULE: false,
 VIEW_SORTIE_VEHICULE:false,
 VIEW_HISTORIQUE_MAINTENANCE: false,
 DELETE_HISTORIQUE_MAINTENANCE:false,
 VIEW_HISTORIQUE_MAINTENANCE_VEHICULE: false,
 DELETE_HISTORIQUE_MAINTENANCE_VEHICULE: false,
 //EndMaintenace
      ADD_SOUS_FAMILLES_ARTICLES: false,
      DELETE_SOUS_FAMILLES_ARTICLES: false,
      MODIFY_SOUS_FAMILLES_ARTICLES: false,
      VIEW_SOUS_FAMILLES_ARTICLES: false,
      VIEW_FAMILLES_ARTICLES: false,
      ADD_FAMILLES_ARTICLES: false,
      MODIFY_FAMILLES_ARTICLES: false,
      DELETE_FAMILLES_ARTICLES: false,
      VIEW_ALERTES: false,
      ADD_ALERTES: false,
      MODIFY_ALERTES: false,
      DELETE_ALERTES: false,
      VIEW_USERS: false,
      ADD_USERS: false,
      MODIFY_USERS: false,
      DELETE_USERS: false,
      VIEW_MESSAGES_APPLICATIFS: false,
      ADD_MESSAGES_APPLICATIFS: false,
      MODIFY_MESSAGES_APPLICATIFS: false,
      DELETE_MESSAGES_APPLICATIFS: false,
      VIEW_TRACABILITES: false,
      DELETE_TRACABILITES: false,
      VIEW_PARAMETRES_APPLICATION: false,
      ADD_PARAMETRES_APPLICATION: false,
      ACTIVATE_USERS: false,
      LOCK_USERS: false,
      MODIFY_PASSWORD_USERS: false,
      RESET_PASSWORD_USERS: false,
      VIEW_CAUSES_SINISTRES: false,
      ADD_CAUSES_SINISTRES: false,
      MODIFY_CAUSES_SINISTRES: false,
      DELETE_CAUSES_SINISTRES: false,
      VIEW_USAGES_VEHICULES: false,
      ADD_USAGES_VEHICULES: false,
      MODIFY_USAGES_VEHICULES: false,
      DELETE_USAGES_VEHICULES: false,
      VIEW_GROUPES_USERS: false,
      ADD_GROUPES_USERS: false,
      MODIFY_GROUPES_USERS: false,
      DELETE_GROUPES_USERS: false,
      VIEW_GPS: false,
      ADD_GPS: false,
      MODIFY_GPS: false,
      DELETE_GPS: false,
      MODIFY_PARAMETRES_APPLICATION: false,
      VIEW_VEHICULE: false,
      ADD_VEHICULE: false,
      MODIFY_VEHICULE: false,
      DELETE_VEHICULE: false,
      VIEW_TAXE_CIRCULATION: false,
      ADD_TAXE_CIRCULATION: false,
      MODIFY_TAXE_CIRCULATION: false,
      DELETE_TAXE_CIRCULATION: false,
      VIEW_ASSURANCE: false,
      ADD_ASSURANCE: false,
      MODIFY_ASSURANCE: false,
      DELETE_ASSURANCE: false,
      VIEW_VISITE_TECHNIQUE: false,
      ADD_VISITE_TECHNIQUE: false,
      MODIFY_VISITE_TECHNIQUE: false,
      DELETE_VISITE_TECHNIQUE: false,
      VIEW_REFORME: false,
      ADD_REFORME: false,
      MODIFY_REFORME: false,
      DELETE_REFORME: false,
      VIEW_BONCOMMANDE:false,
      ADD_BONCOMMANDE:false,
      MODIFY_BONCOMMANDE:false,
      DELETE_BONCOMMANDE:false,
  VIEW_DEMANDE_AFFECTATION:false,
  MODIFY_DEMANDE_AFFECTATION:false,
  DELETE_DEMANDE_AFFECTATION:false,
  ADD_DEMANDE_AFFECTATION:false,
  VIEW_DEMANDE_DESAFECTAION:false,
  MODIFY_DEMANDE_DESAFECTATION:false,
  DELETE_DEMANDE_DESAFECTATION:false,
  VIEW_DECLARATION_PERTE:false,
  ADD_DECLARATION_PERTE:false,
  DELETE_DECLARATION_PERTE:false,
  MODIFY_DECLARATION_PERTE:false,
  VIEW_HISTORIQUE_DECLARATION_PERTE:false,
  DELETE_HISTORIQUE_DECLARATION_PERTE:false,
  VIEW_DEMANDE_QUOTA:false,
  MODIFY_DEMANDE_QUOTA:false,
  DELETE_DEMANDE_QUOTA:false,
  ADD_DEMANDE_QUOTA:false,
  


  VIEW_AGILIS_CASH:false,
  ADD_AGILIS_CASH:false,
  MODIFY_AGILIS_CASH:false,
  DELETE_AGILIS_CASH:false,
  VEHICULE_AGILIS_CASH:false,

  VIEW_RECHARGE_AGILIS:false,
  ADD_RECHARGE_AGILIS:false,
  MODIFY_RECHARGE_AGILIS:false,
  DELETE_RECHARGE_AGILIS:false,
  VEHICULE_RECHARGE_AGILIS:false,
  CONFIRMER_RECHARGE_AGILIS:false,
  VALIDER_RECHARGE_AGILIS:false,

  VIEW_DECLARATION_PERTE_AGILIS:false,
  DELETE_DECLARATION_PERTE_AGILIS:false,
  MODIFY_DECLARATION_PERTE_AGILIS:false,
  ADD_DECLARATION_PERTE_AGILIS:false,
  CONFIRMER_DECLARATION_PERTE_AGILIS:false,

  VIEW_HISTORIQUE_PERTE_AGILIS:false,
  DELETE_HISTORIQUE_PERTE_AGILIS:false,

  VIEW_ANNULATION_AGILIS:false,
  ADD_ANNULATION_AGILIS:false,
  MODIFY_ANNULATION_AGILIS:false,
  DELETE_ANNULATION_AGILIS:false,

  //Ordre de mission
  VIEW_ORDRE_MISSION :false,
  ADD_ORDRE_MISSION:false,
  MODIFY_ORDRE_MISSION: false,
  DELETE_ORDRE_MISSION:false,
  VEHICULE_ORDRE_MISSION:false,
  CONFIRMER_ORDRE_MISSION:false,
  VEHICULE_VEHICULE_DEPASSANT:false,
  DELETE_VEHICULE_DEPASSANT:false,     
  DETAILS_VEHICULE_DEPASSANT :false, 
  VIEW_VEHICULE_DEPASSANT :false,
//Ordre de mission
  //ACHAT
MODIFY_BON_COMMANDE: false,
DELETE_BON_COMMANDE: false,
VIEW_BON_COMMANDE:false,
ADD_BON_COMMANDE:false,

      //REFERENTIEL
      VIEW_ARTICLES: false,
      ADD_ARTICLES: false,
      MODIFY_ARTICLES: false,
      DELETE_ARTICLES: false,
      VIEW_GOUVERNORATS: false,
      ADD_GOUVERNORATS: false,
      MODIFY_GOUVERNORATS: false,
      DELETE_GOUVERNORATS: false,
      VIEW_STATIONS_PEAGE: false,
      ADD_STATIONS_PEAGE: false,
      MODIFY_STATIONS_PEAGE: false,
      DELETE_STATIONS_PEAGE: false,
      VIEW_EXPERTS: false,
      ADD_EXPERTS: false,
      MODIFY_EXPERTS: false,
      DELETE_EXPERTS: false,
      VIEW_FOURNISSEURS: false,
      ADD_FOURNISSEURS: false,
      MODIFY_FOURNISSEURS: false,
      DELETE_FOURNISSEURS: false,
      VIEW_LIEUX_PARKING: false,
      ADD_LIEUX_PARKING: false,
      MODIFY_LIEUX_PARKING: false,
      DELETE_LIEUX_PARKING: false,
      VIEW_FAMILLES_OPERATIONS_REPARATION: false,
      ADD_FAMILLES_OPERATIONS_REPARATION: false,
      MODIFY_FAMILLES_OPERATIONS_REPARATION: false,
      DELETE_FAMILLES_OPERATIONS_REPARATION: false,
      VIEW_OPERATIONS_REPARATION: false,
      ADD_OPERATIONS_REPARATION: false,
      MODIFY_OPERATIONS_REPARATION: false,
      DELETE_OPERATIONS_REPARATION: false,
      VIEW_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
      ADD_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
      MODIFY_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
      DELETE_PROGRAMMES_ENTRETIENS_PREVENTIFS: false,
      VIEW_ANNEES: false,
      ADD_ANNEES: false,
      DELETE_ANNEES: false,
      VIEW_ENERGIES: false,
      ADD_ENERGIES: false,
      MODIFY_ENERGIES: false,
      DELETE_ENERGIES: false,
      VIEW_TVA: false,
      ADD_TVA: false,
      MODIFY_TVA: false,
      DELETE_TVA: false,
      VIEW_UNITES: false,
      ADD_UNITES: false,
      DELETE_UNITES: false,
      VIEW_GENRES_VEHICULE: false,
      ADD_GENRES_VEHICULE: false,
      MODIFY_GENRES_VEHICULE: false,
      DELETE_GENRES_VEHICULE: false,
      VIEW_MARQUES_VEHICULE: false,
      ADD_MARQUES_VEHICULE: false,
      MODIFY_MARQUES_VEHICULE: false,
      DELETE_MARQUES_VEHICULE: false,
      VIEW_TYPES_VEHICULE: false,
      ADD_TYPES_VEHICULE: false,
      MODIFY_TYPES_VEHICULE: false,
      DELETE_TYPES_VEHICULE: false,
      VIEW_STRUCTURE_ADMINISTRATIVE: false,
      ADD_STRUCTURE_ADMINISTRATIVE: false,
      MODIFY_STRUCTURE_ADMINISTRATIVE: false,
      DELETE_STRUCTURE_ADMINISTRATIVE: false,
      VIEW_UNITE_GESTION_PARC: false,
      ADD_UNITE_GESTION_PARC: false,
      MODIFY_UNITE_GESTION_PARC: false,
      DELETE_UNITE_GESTION_PARC: false,
      VIEW_DETAILS_PERSONNELS: false,
      ADD_DETAILS_PERSONNELS: false,
      MODIFY_DETAILS_PERSONNELS: false,
      DELETE_DETAILS_PERSONNELS: false,
      VIEW_ETATS_STOCK: false,
      ADD_ETATS_STOCK: false,
      MODIFY_ETATS_STOCK: false,
      DELETE_ETATS_STOCK: false,
      VIEW_BENEFICIAIRES_EMPRUNTS: false,
      ADD_BENEFICIAIRES_EMPRUNTS: false,
      MODIFY_BENEFICIAIRES_EMPRUNTS: false,
      DELETE_BENEFICIAIRES_EMPRUNTS: false,
      //REFERENTIEL
           
//EXPLOITATION
VIEW_RESERVATION:false,
ADD_RESERVATION:false,
MODIFY_RESERVATION:false,
DELETE_RESERVATION:false,
VIEW_VEHICULE_RESERVATION:false,
CONFIRMER_RESERVATION:false,
VIEW_LOCATION:false,
ADD_LOCATION:false,
MODIFY_LOCATION:false,
DELETE_LOCATION:false,
VIEW_SINISTRE:false,
ADD_SINISTRE:false,
MODIFY_SINISTRE:false,
DELETE_SINISTRE:false,
VIEW_VEHICULE_SINISTRE:false,
VIEW_EMPRUNT:false,
ADD_EMPRUNT:false,
MODIFY_EMPRUNT:false,
DELETE_EMPRUNT:false,
VIEW_VEHICULE_EMPRUNT:false,
CONFIRMER_EMPRUNT:false,
//EXPLOITATION
 
 //CARBURANT : CARTE PLAFOND

 VIEW_CARTE_PLAFOND:false,
 MODIFY_CARTE_PLAFOND:false,
 DELETE_CARTE_PLAFOND:false,
 ADD_CARTE_PLAFOND:false,
 
 VIEW_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 DELETE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 ADD_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 CONFIRM_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 VALIDATION_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 VEHICULE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,

 VIEW_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 DELETE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 VEHICULE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND:false,
 
 VIEW_DECLARATION_PERTE_CARTE_PLAFOND:false,
 MODIFY_DECLARATION_PERTE_CARTE_PLAFOND:false,
 DELETE_DECLARATION_PERTE_CARTE_PLAFOND:false,
 ADD_DECLARATION_PERTE_CARTE_PLAFOND:false,
 CONFIRMATION_DECLARATION_PERTE_CARTE_PLAFOND:false,
 
 VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND:false,
 DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND:false,
 
 ADD_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 
 VIEW_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 MODIFY_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 DELETE_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 CONFIRMATION_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 
 VIEW_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 DELETE_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND:false,
 
 //CARBURANT / CARTE PLAFOND
//stock

DELETE_TRANSFERT_PARC_VERS_MAGASIN:false,
MODIFY_TRANSFERT_PARC_VERS_MAGASIN:false,
CONFIRM_TRANSFERT_PARC_VERS_MAGASIN:false,
VALID_TRANSFERT_PARC_VERS_MAGASIN: false,
ADD_TRANSFERT_PARC_VERS_MAGASIN: false,
VIEW_TRANSFERT_PARC_VERS_MAGASIN: false,

VIEW_Bon_Travail_Sortie:false,
DETAILS_Bon_Travail_Sortie:false,
VIEW_Bon_Transfert_vers_magasin:false,
CONFIRM_Bon_Transfert_vers_magasin :false,
VALIDER_Bon_Transfert_vers_magasin :false,
MODIFY_Bon_Transfert_vers_magasin :false,
DELETE_Bon_Transfert_vers_magasin :false,
ADD_Bon_Transfert_vers_magasin :false,
VIEW_Bon_Sortie_Structure :false,
VIEW_Reception_Fournisseur:false,
DELETE_Reception_Fournisseur :false,
DETAILS_Reception_Fournisseur:false,
VIEW_Reception_Atelier:false,
VIEW_Transfert_magasin:false,
VIEW_Retour_Structure:false,
DETAILS_Retour_Structure:false,
DELETE_Retour_Structure:false,
ADD_Retour_Structure:false,
VIEW_Inventaire_Stock:false,
DETAILS_Inventaire_Stock :false,
DELETE_Inventaire_Stock:false,
ADD_Inventaire_Stock:false,
VIEW_Regulation_Stock:false,
DETAILS_Regulation_Stock:false,
DELETE_Regulation_Stock:false,
ADD_Regulation_Stock:false,
CONFIRMER_ANNULATION_AGILIS :false,
VIEW_HISTORIQUE_REGULATION :false,
DELETE_HISTORIQUE_REGULATION :false,


 //CARBURANT : CARTE JOCKER

 VIEW_CARTE_JOCKER:false,
 MODIFY_CARTE_JOCKER:false,
 DELETE_CARTE_JOCKER:false,
 ADD_CARTE_JOCKER:false,
 
 CONFIRMATION_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
 VALIDATION_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
 VIEW_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
 MODIFY_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
 ADD_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
 VEHICULE_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
 DELETE_DEMANDE_AFFECTATION_CARTE_JOCKER: false,
 
 
 CONFIRMATION_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
 VIEW_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
 MODIFY_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
 DELETE_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
 ADD_DEMANDE_DESAFFECTATION_CARTE_JOCKER: false,
 
 ADD_DECLARATION_PERTE_CARTE_JOCKER: false,
 DELETE_DECLARATION_PERTE_CARTE_JOCKER: false,
 MODIFY_DECLARATION_PERTE_CARTE_JOCKER: false,
 CONFIRMATION_DECLARATION_PERTE_CARTE_JOCKER: false,
 VIEW_DECLARATION_PERTE_CARTE_JOCKER: false,
 
 VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER: false,
 DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER: false,
 
 CONFIRMATION_DEMANDE_QUOTA_CARTE_JOCKER: false,
 VALIDATION_DEMANDE_QUOTA_CARTE_JOCKER: false,
 ADD_DEMANDE_QUOTA_CARTE_JOCKER: false,
 MODIFY_DEMANDE_QUOTA_CARTE_JOCKER: false,
 DELETE_DEMANDE_QUOTA_CARTE_JOCKER: false,
 VIEW_DEMANDE_QUOTA_CARTE_JOCKER: false,

 //CARBURANT : CARTE JOCKER   

 // CARBURANT : Distribution de carburant
ADD_DISTRIBUTION_CARBURANT_FONCTION: false,
MODIFY_DISTRIBUTION_CARBURANT_FONCTION: false,
DELETE_DISTRIBUTION_CARBURANT_FONCTION: false,
VIEW_DISTRIBUTION_CARBURANT_FONCTION: false,
VEHICULE_DISTRIBUTION_CARBURANT_FONCTION: false,

ADD_DISTRIBUTION_CARBURANT_VEHICULE: false,
MODIFY_DISTRIBUTION_CARBURANT_VEHICULE: false,
DELETE_DISTRIBUTION_CARBURANT_VEHICULE: false,
VIEW_DISTRIBUTION_CARBURANT_VEHICULE: false,

ADD_DESTRIBUTION_CARBURANT_SERVICE: false,
MODIFY_DESTRIBUTION_CARBURANT_SERVICE: false,
DELETE_DESTRIBUTION_CARBURANT_SERVICE: false,
VIEW_DESTRIBUTION_CARBURANT_SERVICE: false,
VEHICULE_DESTRIBUTION_CARBURANT_SERVICE: false,

ADD_DESTRIBUTION_CARBURANT_COMPENSATION: false,
MODIFY_DESTRIBUTION_CARBURANT_COMPENSATION: false,
DELETE_DESTRIBUTION_CARBURANT_COMPENSATION: false,
VIEW_DESTRIBUTION_CARBURANT_COMPENSATION: false,
VEHICULE_DESTRIBUTION_CARBURANT_COMPENSATION: false,

ADD_TRANSFERT_PARC: false,
VIEW_TRANSFERT_PARC: false,
DETAIL_TRANSFERT_PARC: false,

ADD_RETOUR_CARBURANT: false,
VIEW_RETOUR_CARBURANT: false,

ADD_ETAT_MENSUEL: false,
MODIFY_ETAT_MENSUEL: false,
DELETE_ETAT_MENSUEL: false,
VIEW_ETAT_MENSUEL: false,
VEHICULE_ETAT_MENSUEL: false,
VALIDER_ETAT_MENSUEL: false,
CONFIRMER_ETAT_MENSUEL: false,

ADD_BON_CARBURANT_BON: false,
VIEW_BON_CARBURANT_BON: false,

ADD_SUIVI: false,
VIEW_SUIVI: false,
VIEW_DEMANDE_RECHARGE_SOUS_COMPTE: false,
ADD_DEMANDE_RECHARGE_SOUS_COMPTE : false,
VALID_DEMANDE_RECHARGE_SOUS_COMPTE : false,
CONFIRM_DEMANDE_RECHARGE_SOUS_COMPTE : false,
DELETE_DEMANDE_RECHARGE_SOUS_COMPTE: false,
// CARBURANT : Distribution de carburant

    };
//alert

if (authorities.includes('VIEW_ALERT_VEHICULE ')) {
  this.authoritiesUtilisateur.VIEW_ALERT_VEHICULE  = true;
} 
if (authorities.includes('VIEW_ALERT_STOCK ')) {
  this.authoritiesUtilisateur.VIEW_ALERT_STOCK  = true;
} 
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 

if (authorities.includes('CONFIRMATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.CONFIRMATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION = true;
} 
if (authorities.includes('VALIDATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.VALIDATION_DEMANDE_RECHARGE_CARBURANT_COMPENSATION = true;
} 
if (authorities.includes('ADD_DEMANDE_RECHARGE_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_RECHARGE_CARBURANT_COMPENSATION = true;
} 
if (authorities.includes('MODIFY_DEMANDE_RECHARGE_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.MODIFY_DEMANDE_RECHARGE_CARBURANT_COMPENSATION = true;
} 
if (authorities.includes('DELETE_RECHARGE_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.DELETE_RECHARGE_CARBURANT_COMPENSATION = true;
} 
if (authorities.includes('VIEW_DEMANDE_RECHARGE_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_RECHARGE_CARBURANT_COMPENSATION = true;
} 
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 

//CARBURANT : RECHARGE DE QUOTA MENSUEL 

if (authorities.includes('CONFIRM_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.CONFIRM_RECHARGE_QUOTA_MENSUEL = true;
} 
if (authorities.includes('VALID_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.VALID_RECHARGE_QUOTA_MENSUEL = true;
} 
if (authorities.includes('ADD_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.ADD_RECHARGE_QUOTA_MENSUEL = true;
} 
if (authorities.includes('VIEW_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.VIEW_RECHARGE_QUOTA_MENSUEL = true;
} 
//CARBURANT : RECHARGE DE QUOTA MENSUEL 

//CARBURANT : historique RECHARGE DE QUOTA MENSUEL
if (authorities.includes('VIEW_HISTORIQUE_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_RECHARGE_QUOTA_MENSUEL = true;
} 
//CARBURANT : historique RECHARGE DE QUOTA MENSUEL 


    if (authorities.includes('VIEW_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE')) {
      this.authoritiesUtilisateur.VIEW_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE = true;
    } 
    if (authorities.includes('DELETE_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE')) {
      this.authoritiesUtilisateur.DELETE_HISTORIQUE_DEMANDE_RECHARGE_SOUS_COMPTE = true;
    } 
     
//Maintenace :
if (authorities.includes('DETAILS_BON_TRAVAIL')) {
  this.authoritiesUtilisateur.DETAILS_BON_TRAVAIL = true;
} 
if (authorities.includes('DELETE_BON_TRAVAIL')) {
  this.authoritiesUtilisateur.DELETE_BON_TRAVAIL = true;
} 
if (authorities.includes('VIEW_BON_TRAVAIL')) {
  this.authoritiesUtilisateur.VIEW_BON_TRAVAIL = true;
} 
if (authorities.includes('ADD_BON_TRAVAIL')) {
  this.authoritiesUtilisateur.ADD_BON_TRAVAIL = true;
} 
if (authorities.includes('MODIFY_SORTIE_VEHICULE')) {
  this.authoritiesUtilisateur.MODIFY_SORTIE_VEHICULE = true;
} 
if (authorities.includes('VIEW_SORTIE_VEHICULE')) {
  this.authoritiesUtilisateur.VIEW_SORTIE_VEHICULE = true;
} 

if (authorities.includes('MODIFY_DEMANDE_INTERVENTION')) {
  this.authoritiesUtilisateur.MODIFY_DEMANDE_INTERVENTION = true;
} 
if (authorities.includes('DELETE_DEMANDE_INTERVENTION')) {
  this.authoritiesUtilisateur.DELETE_DEMANDE_INTERVENTION = true;
} 
if (authorities.includes('VIEW_DEMANDE_INTERVENTION')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_INTERVENTION = true;
} 
if (authorities.includes('ADD_DEMANDE_INTERVENTION')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_INTERVENTION = true;
} 

if (authorities.includes('VIEW_HISTORIQUE_MAINTENANCE_VEHICULE')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_MAINTENANCE_VEHICULE = true;
} 
if (authorities.includes('DELETE_HISTORIQUE_MAINTENANCE_VEHICULE')) {
  this.authoritiesUtilisateur.DELETE_HISTORIQUE_MAINTENANCE_VEHICULE= true;
} 
  //End Maintenace 


  
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 

if (authorities.includes('CONFIRMATION_DEMANDE_RECHARGE_COMPLEMENTAIRE')) {
  this.authoritiesUtilisateur.CONFIRMATION_DEMANDE_RECHARGE_COMPLEMENTAIRE = true;
} 
if (authorities.includes('VALIDATION_DEMANDE_RECHARGE_COMPLEMENTAIRE')) {
  this.authoritiesUtilisateur.VALIDATION_DEMANDE_RECHARGE_COMPLEMENTAIRE = true;
} 
if (authorities.includes('ADD_DEMANDE_RECHARGE_COMPLEMENTAIRE')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_RECHARGE_COMPLEMENTAIRE = true;
} 
if (authorities.includes('MODIFY_DEMANDE_RECHARGE_COMPLEMENTAIRE')) {
  this.authoritiesUtilisateur.MODIFY_DEMANDE_RECHARGE_COMPLEMENTAIRE = true;
} 
if (authorities.includes('DELETE_RECHARGE_COMPLEMENTAIRE')) {
  this.authoritiesUtilisateur.DELETE_RECHARGE_COMPLEMENTAIRE = true;
} 
if (authorities.includes('VIEW_DEMANDE_RECHARGE_COMPLEMENTAIRE')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_RECHARGE_COMPLEMENTAIRE = true;
} 
//CARBURANT : RECHARGE DE CARBURANT DE COMPENSATION 




  if (authorities.includes('VIEW_DEMANDE_RECHARGE_SOUS_COMPTE')) {
    this.authoritiesUtilisateur.VIEW_DEMANDE_RECHARGE_SOUS_COMPTE = true;
  } 
  if (authorities.includes('ADD_DEMANDE_RECHARGE_SOUS_COMPTE')) {
    this.authoritiesUtilisateur.ADD_DEMANDE_RECHARGE_SOUS_COMPTE = true;
  } 
  if (authorities.includes('VALID_DEMANDE_RECHARGE_SOUS_COMPTE')) {
    this.authoritiesUtilisateur.VALID_DEMANDE_RECHARGE_SOUS_COMPTE = true;
  } 
  if (authorities.includes('CONFIRM_DEMANDE_RECHARGE_SOUS_COMPTE')) {
    this.authoritiesUtilisateur.CONFIRM_DEMANDE_RECHARGE_SOUS_COMPTE = true;
  } 
  if (authorities.includes('DELETE_DEMANDE_RECHARGE_SOUS_COMPTE')) {
    this.authoritiesUtilisateur.DELETE_DEMANDE_RECHARGE_SOUS_COMPTE = true;
  } 
 



  if (authorities.includes('DELETE_ANNULATION_AGILIS')) {
    this.authoritiesUtilisateur.DELETE_ANNULATION_AGILIS = true;
  } 
  if (authorities.includes('MODIFY_ANNULATION_AGILIS')) {
    this.authoritiesUtilisateur.MODIFY_ANNULATION_AGILIS = true;
  } 
  if (authorities.includes('ADD_ANNULATION_AGILIS')) {
    this.authoritiesUtilisateur.ADD_ANNULATION_AGILIS = true;
  } 
  if (authorities.includes('VIEW_ANNULATION_AGILIS')) {
    this.authoritiesUtilisateur.VIEW_ANNULATION_AGILIS = true;
  } 
  if (authorities.includes('CONFIRMER_RECHARGE_AGILIS')) {
    this.authoritiesUtilisateur.CONFIRMER_RECHARGE_AGILIS = true;
  } 
  if (authorities.includes('VALIDER_RECHARGE_AGILIS')) {
    this.authoritiesUtilisateur.VALIDER_RECHARGE_AGILIS = true;
  } 
  if (authorities.includes('DELETE_HISTORIQUE_PERTE_AGILIS')) {
    this.authoritiesUtilisateur.DELETE_HISTORIQUE_PERTE_AGILIS = true;
  } 
  if (authorities.includes('VIEW_HISTORIQUE_PERTE_AGILIS')) {
    this.authoritiesUtilisateur.VIEW_HISTORIQUE_PERTE_AGILIS = true;
  } 
  if (authorities.includes('CONFIRMER_DECLARATION_PERTE_AGILIS')) {
    this.authoritiesUtilisateur.CONFIRMER_DECLARATION_PERTE_AGILIS = true;
  } 
  if (authorities.includes('ADD_DECLARATION_PERTE_AGILIS')) {
    this.authoritiesUtilisateur.ADD_DECLARATION_PERTE_AGILIS = true;
  } 
  if (authorities.includes('MODIFY_DECLARATION_PERTE_AGILIS')) {
    this.authoritiesUtilisateur.MODIFY_DECLARATION_PERTE_AGILIS = true;
  } 
  if (authorities.includes('DELETE_DECLARATION_PERTE_AGILIS')) {
    this.authoritiesUtilisateur.DELETE_DECLARATION_PERTE_AGILIS = true;
  } 
  if (authorities.includes('VIEW_DECLARATION_PERTE_AGILIS')) {
    this.authoritiesUtilisateur.VIEW_DECLARATION_PERTE_AGILIS = true;
  } 
  if (authorities.includes('VEHICULE_RECHARGE_AGILIS')) {
    this.authoritiesUtilisateur.VEHICULE_RECHARGE_AGILIS = true;
  } 
  if (authorities.includes('DELETE_RECHARGE_AGILIS')) {
    this.authoritiesUtilisateur.DELETE_RECHARGE_AGILIS = true;
  } 
  if (authorities.includes('MODIFY_RECHARGE_AGILIS')) {
    this.authoritiesUtilisateur.MODIFY_RECHARGE_AGILIS = true;
  } 
  if (authorities.includes('ADD_RECHARGE_AGILIS')) {
    this.authoritiesUtilisateur.ADD_RECHARGE_AGILIS = true;
  } 
  if (authorities.includes('VIEW_RECHARGE_AGILIS')) {
    this.authoritiesUtilisateur.VIEW_RECHARGE_AGILIS = true;
  } 
  if (authorities.includes('VEHICULE_AGILIS_CASH')) {
    this.authoritiesUtilisateur.VEHICULE_AGILIS_CASH = true;
  } 
  if (authorities.includes('DELETE_AGILIS_CASH')) {
    this.authoritiesUtilisateur.DELETE_AGILIS_CASH = true;
  } 
  if (authorities.includes('MODIFY_AGILIS_CASH')) {
    this.authoritiesUtilisateur.MODIFY_AGILIS_CASH = true;
  } 
  if (authorities.includes('ADD_AGILIS_CASH')) {
    this.authoritiesUtilisateur.ADD_AGILIS_CASH = true;
  } 
  if (authorities.includes('VIEW_AGILIS_CASH')) {
    this.authoritiesUtilisateur.VIEW_AGILIS_CASH = true;
  } 


    if (authorities.includes('ADD_DEMANDE_QUOTA')) {
      this.authoritiesUtilisateur.ADD_DEMANDE_QUOTA = true;
    } 
    if (authorities.includes('DELETE_DEMANDE_QUOTA')) {
      this.authoritiesUtilisateur.DELETE_DEMANDE_QUOTA = true;
    } 
    if (authorities.includes('MODIFY_DEMANDE_QUOTA')) {
      this.authoritiesUtilisateur.MODIFY_DEMANDE_QUOTA = true;
    } 
    if (authorities.includes('VIEW_DEMANDE_QUOTA')) {
      this.authoritiesUtilisateur.VIEW_DEMANDE_QUOTA = true;
    } 
    if (authorities.includes('DELETE_HISTORIQUE_DECLARATION_PERTE')) {
      this.authoritiesUtilisateur.DELETE_HISTORIQUE_DECLARATION_PERTE = true;
    } 
    if (authorities.includes('VIEW_HISTORIQUE_DECLARATION_PERTE')) {
      this.authoritiesUtilisateur.VIEW_HISTORIQUE_DECLARATION_PERTE = true;
    } 
    if (authorities.includes('MODIFY_DECLARATION_PERTE')) {
      this.authoritiesUtilisateur.MODIFY_DECLARATION_PERTE = true;
    } 
    if (authorities.includes('DELETE_DECLARATION_PERTE')) {
      this.authoritiesUtilisateur.DELETE_DECLARATION_PERTE = true;
    } 
    if (authorities.includes('ADD_DECLARATION_PERTE')) {
      this.authoritiesUtilisateur.ADD_DECLARATION_PERTE = true;
    } 
    if (authorities.includes('VIEW_DECLARATION_PERTE')) {
      this.authoritiesUtilisateur.VIEW_DECLARATION_PERTE = true;
    } 
    if (authorities.includes('DELETE_DEMANDE_DESAFECTATION')) {
      this.authoritiesUtilisateur.DELETE_DEMANDE_DESAFECTATION = true;
    } 
    if (authorities.includes('MODIFY_DEMANDE_DESAFECTATION')) {
      this.authoritiesUtilisateur.MODIFY_DEMANDE_DESAFECTATION = true;
    } 
    if (authorities.includes('VIEW_DEMANDE_DESAFECTAION')) {
      this.authoritiesUtilisateur.VIEW_DEMANDE_DESAFECTAION = true;
    } 
    if (authorities.includes('ADD_DEMANDE_AFFECTATION')) {
      this.authoritiesUtilisateur.ADD_DEMANDE_AFFECTATION = true;
    } 
    if (authorities.includes('DELETE_DEMANDE_AFFECTATION')) {
      this.authoritiesUtilisateur.DELETE_DEMANDE_AFFECTATION = true;
    } 
    if (authorities.includes('MODIFY_DEMANDE_AFFECTATION')) {
      this.authoritiesUtilisateur.MODIFY_DEMANDE_AFFECTATION = true;
    } 
    if (authorities.includes('VIEW_DEMANDE_AFFECTATION')) {
      this.authoritiesUtilisateur.VIEW_DEMANDE_AFFECTATION = true;
    } 

    if (authorities.includes('DELETE_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.DELETE_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
    } 
     if (authorities.includes('VIEW_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.VIEW_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('DELETE_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.DELETE_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('MODIFY_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.MODIFY_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('VIEW_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.VIEW_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('ADD_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.ADD_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('ADD_DECLARATION_PERTE_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.ADD_DECLARATION_PERTE_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('DELETE_DECLARATION_PERTE_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.DELETE_DECLARATION_PERTE_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('MODIFY_DECLARATION_PERTE_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.MODIFY_DECLARATION_PERTE_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('VIEW_DECLARATION_PERTE_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.VIEW_DECLARATION_PERTE_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('DELETE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.DELETE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('VIEW_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.VIEW_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('ADD_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.ADD_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('DELETE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.DELETE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('VIEW_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.VIEW_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('ADD_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.ADD_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('DELETE_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.DELETE_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('MODIFY_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.MODIFY_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('VIEW_CARTE_PLAFOND')) {
      this.authoritiesUtilisateur.VIEW_CARTE_PLAFOND = true;
    } 
    if (authorities.includes('VIEW_RESERVATION')) {
      this.authoritiesUtilisateur.VIEW_RESERVATION = true;
    } 
    if (authorities.includes('VIEW_VEHICULE_EMPRUNT')) {
      this.authoritiesUtilisateur.VIEW_VEHICULE_EMPRUNT = true;
    }
    if (authorities.includes('DELETE_EMPRUNT')) {
      this.authoritiesUtilisateur.DELETE_EMPRUNT = true;
    }
    if (authorities.includes('MODIFY_EMPRUNT')) {
      this.authoritiesUtilisateur.MODIFY_EMPRUNT = true;
    } 
    if (authorities.includes('ADD_EMPRUNT')) {
      this.authoritiesUtilisateur.ADD_EMPRUNT = true;
    }
     if (authorities.includes('VIEW_EMPRUNT')) {
      this.authoritiesUtilisateur.VIEW_EMPRUNT = true;
    } 
    if (authorities.includes('VIEW_VEHICULE_SINISTRE')) {
      this.authoritiesUtilisateur.VIEW_VEHICULE_SINISTRE = true;
    } 
    if (authorities.includes('DELETE_SINISTRE')) {
      this.authoritiesUtilisateur.DELETE_SINISTRE = true;
    }
     if (authorities.includes('MODIFY_SINISTRE')) {
      this.authoritiesUtilisateur.MODIFY_SINISTRE = true;
    }
     if (authorities.includes('ADD_SINISTRE')) {
      this.authoritiesUtilisateur.ADD_SINISTRE = true;
    }
     if (authorities.includes('VIEW_SINISTRE')) {
      this.authoritiesUtilisateur.VIEW_SINISTRE = true;
    } 
    if (authorities.includes('DELETE_LOCATION')) {
      this.authoritiesUtilisateur.DELETE_LOCATION = true;
    }
     if (authorities.includes('MODIFY_LOCATION')) {
      this.authoritiesUtilisateur.MODIFY_LOCATION = true;
    } 
    if (authorities.includes('ADD_LOCATION')) {
      this.authoritiesUtilisateur.ADD_LOCATION = true;
    } 
    if (authorities.includes('VIEW_LOCATION')) {
      this.authoritiesUtilisateur.VIEW_LOCATION = true;
    }
     if (authorities.includes('VIEW_VEHICULE_RESERVATION')) {
      this.authoritiesUtilisateur.VIEW_VEHICULE_RESERVATION = true;
    } 
    if (authorities.includes('DELETE_RESERVATION')) {
      this.authoritiesUtilisateur.DELETE_RESERVATION = true;
    }
    if (authorities.includes('MODIFY_RESERVATION')) {
      this.authoritiesUtilisateur.MODIFY_RESERVATION = true;
    }
    if (authorities.includes('ADD_RESERVATION')) {
      this.authoritiesUtilisateur.ADD_RESERVATION = true;
    }

    if (authorities.includes('ADD_SOUS_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.ADD_SOUS_FAMILLES_ARTICLES = true;
    }
    if (authorities.includes('DELETE_SOUS_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.DELETE_SOUS_FAMILLES_ARTICLES = true;
    }
    if (authorities.includes('MODIFY_SOUS_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.MODIFY_SOUS_FAMILLES_ARTICLES = true;
    }
    if (authorities.includes('VIEW_SOUS_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.VIEW_SOUS_FAMILLES_ARTICLES = true;
    }
    if (authorities.includes('VIEW_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.VIEW_FAMILLES_ARTICLES = true;
    }
    if (authorities.includes('ADD_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.ADD_FAMILLES_ARTICLES = true;
    }
    if (authorities.includes('MODIFY_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.MODIFY_FAMILLES_ARTICLES = true;
    }
    if (authorities.includes('DELETE_FAMILLES_ARTICLES')) {
      this.authoritiesUtilisateur.DELETE_FAMILLES_ARTICLES = true;
    }

    if (authorities.includes('VIEW_ALERTES')) {
      this.authoritiesUtilisateur.VIEW_ALERTES = true;
    }
    if (authorities.includes('ADD_ALERTES')) {
      this.authoritiesUtilisateur.ADD_ALERTES = true;
    }
    if (authorities.includes('MODIFY_ALERTES')) {
      this.authoritiesUtilisateur.MODIFY_ALERTES = true;
    }
    if (authorities.includes('DELETE_ALERTES')) {
      this.authoritiesUtilisateur.DELETE_ALERTES = true;
    }
    if (authorities.includes('VIEW_USERS')) {
      this.authoritiesUtilisateur.VIEW_USERS = true;
    }
    if (authorities.includes('ADD_USERS')) {
      this.authoritiesUtilisateur.ADD_USERS = true;
    }
    if (authorities.includes('MODIFY_USERS')) {
      this.authoritiesUtilisateur.MODIFY_USERS = true;
    }
    if (authorities.includes('DELETE_USERS')) {
      this.authoritiesUtilisateur.DELETE_USERS = true;
    }
    if (authorities.includes('VIEW_MESSAGES_APPLICATIFS')) {
      this.authoritiesUtilisateur.VIEW_MESSAGES_APPLICATIFS = true;
    }
    if (authorities.includes('ADD_MESSAGES_APPLICATIFS')) {
      this.authoritiesUtilisateur.ADD_MESSAGES_APPLICATIFS = true;
    }
    if (authorities.includes('MODIFY_MESSAGES_APPLICATIFS')) {
      this.authoritiesUtilisateur.MODIFY_MESSAGES_APPLICATIFS = true;
    }
    if (authorities.includes('DELETE_MESSAGES_APPLICATIFS')) {
      this.authoritiesUtilisateur.DELETE_MESSAGES_APPLICATIFS = true;
    }
    if (authorities.includes('VIEW_TRACABILITES')) {
      this.authoritiesUtilisateur.VIEW_TRACABILITES = true;
    }
    if (authorities.includes('DELETE_TRACABILITES')) {
      this.authoritiesUtilisateur.DELETE_TRACABILITES = true;
    }
    if (authorities.includes('VIEW_USERS')) {
      this.authoritiesUtilisateur.VIEW_USERS = true;
    }
    if (authorities.includes('LOCK_USERS')) {
      this.authoritiesUtilisateur.LOCK_USERS = true;
    }
    if (authorities.includes('MODIFY_PASSWORD_USERS')) {
      this.authoritiesUtilisateur.MODIFY_PASSWORD_USERS = true;
    }
    if (authorities.includes('RESET_PASSWORD_USERS')) {
      this.authoritiesUtilisateur.RESET_PASSWORD_USERS = true;
    }
    if (authorities.includes('VIEW_TVA')) {
      this.authoritiesUtilisateur.VIEW_TVA = true;
    }
    if (authorities.includes('DELETE_CAUSES_SINISTRES')) {
      this.authoritiesUtilisateur.DELETE_CAUSES_SINISTRES = true;
    }
    if (authorities.includes('MODIFY_CAUSES_SINISTRES')) {
      this.authoritiesUtilisateur.MODIFY_CAUSES_SINISTRES = true;
    }
    if (authorities.includes('ADD_CAUSES_SINISTRES')) {
      this.authoritiesUtilisateur.ADD_CAUSES_SINISTRES = true;
    }
    if (authorities.includes('VIEW_CAUSES_SINISTRES')) {
      this.authoritiesUtilisateur.VIEW_CAUSES_SINISTRES = true;
    }
    if (authorities.includes('VIEW_GROUPES_USERS')) {
      this.authoritiesUtilisateur.VIEW_GROUPES_USERS = true;
    }
    if (authorities.includes('ADD_GROUPES_USERS')) {
      this.authoritiesUtilisateur.ADD_GROUPES_USERS = true;
    }
    if (authorities.includes('MODIFY_GROUPES_USERS')) {
      this.authoritiesUtilisateur.MODIFY_GROUPES_USERS = true;
    }
    if (authorities.includes('VIEW_GROUPES_USERS')) {
      this.authoritiesUtilisateur.VIEW_GROUPES_USERS = true;
    }
    if (authorities.includes('VIEW_GPS')) {
      this.authoritiesUtilisateur.VIEW_GPS = true;
    }
    if (authorities.includes('ADD_GPS')) {
      this.authoritiesUtilisateur.ADD_GPS = true;
    }
    if (authorities.includes('MODIFY_GPS')) {
      this.authoritiesUtilisateur.MODIFY_GPS = true;
    }
    if (authorities.includes('DELETE_GPS')) {
      this.authoritiesUtilisateur.DELETE_GPS = true;
    }
    if (authorities.includes('VIEW_TRACABILITES')) {
      this.authoritiesUtilisateur.VIEW_TRACABILITES = true;
    }
    if (authorities.includes('DELETE_TRACABILITES')) {
      this.authoritiesUtilisateur.DELETE_TRACABILITES = true;
    }
    if (authorities.includes('VIEW_USAGES_VEHICULES')) {
      this.authoritiesUtilisateur.VIEW_USAGES_VEHICULES = true;
    }
    if (authorities.includes('ADD_USAGES_VEHICULES')) {
      this.authoritiesUtilisateur.ADD_USAGES_VEHICULES = true;
    }
    if (authorities.includes('MODIFY_USAGES_VEHICULES')) {
      this.authoritiesUtilisateur.MODIFY_USAGES_VEHICULES = true;
    }
    if (authorities.includes('DELETE_USAGES_VEHICULES')) {
      this.authoritiesUtilisateur.DELETE_USAGES_VEHICULES = true;
    }
    if (authorities.includes('ACTIVATE_USERS')) {
      this.authoritiesUtilisateur.ACTIVATE_USERS = true;
    }
    if (authorities.includes('DELETE_GROUPES_USERS')) {
      this.authoritiesUtilisateur.DELETE_GROUPES_USERS = true;
    }
    if (authorities.includes('VIEW_PARAMETRES_APPLICATION')) {
      this.authoritiesUtilisateur.VIEW_PARAMETRES_APPLICATION = true;
    }
    if (authorities.includes('ADD_PARAMETRES_APPLICATION')) {
      this.authoritiesUtilisateur.ADD_PARAMETRES_APPLICATION = true;
    }
    if (authorities.includes('MODIFY_PARAMETRES_APPLICATION')) {
      this.authoritiesUtilisateur.MODIFY_PARAMETRES_APPLICATION = true;
    }
    if (authorities.includes('VIEW_VEHICULE')) {
      this.authoritiesUtilisateur.VIEW_VEHICULE = true;
    }
    if (authorities.includes('ADD_VEHICULE')) {
      this.authoritiesUtilisateur.ADD_VEHICULE = true;
    }
    if (authorities.includes('MODIFY_VEHICULE')) {
      this.authoritiesUtilisateur.MODIFY_VEHICULE = true;
    }
    if (authorities.includes('DELETE_VEHICULE')) {
      this.authoritiesUtilisateur.DELETE_VEHICULE = true;
    }
    if (authorities.includes('VIEW_TAXE_CIRCULATION')) {
      this.authoritiesUtilisateur.VIEW_TAXE_CIRCULATION = true;
    }
    if (authorities.includes('ADD_TAXE_CIRCULATION')) {
      this.authoritiesUtilisateur.ADD_TAXE_CIRCULATION = true;
    }
    if (authorities.includes('MODIFY_TAXE_CIRCULATION')) {
      this.authoritiesUtilisateur.MODIFY_TAXE_CIRCULATION = true;
    }
    if (authorities.includes('DELETE_TAXE_CIRCULATION')) {
      this.authoritiesUtilisateur.DELETE_TAXE_CIRCULATION = true;
    }
    if (authorities.includes('VIEW_ASSURANCE')) {
      this.authoritiesUtilisateur.VIEW_ASSURANCE = true;
    }
    if (authorities.includes('ADD_ASSURANCE')) {
      this.authoritiesUtilisateur.ADD_ASSURANCE = true;
    }
    if (authorities.includes('MODIFY_ASSURANCE')) {
      this.authoritiesUtilisateur.MODIFY_ASSURANCE = true;
    }
    if (authorities.includes('DELETE_ASSURANCE')) {
      this.authoritiesUtilisateur.DELETE_ASSURANCE = true;
    }
    if (authorities.includes('VIEW_VISITE_TECHNIQUE')) {
      this.authoritiesUtilisateur.VIEW_VISITE_TECHNIQUE = true;
    }
    if (authorities.includes('ADD_VISITE_TECHNIQUE')) {
      this.authoritiesUtilisateur.ADD_VISITE_TECHNIQUE = true;
    }
    if (authorities.includes('MODIFY_VISITE_TECHNIQUE')) {
      this.authoritiesUtilisateur.MODIFY_VISITE_TECHNIQUE = true;
    }
    if (authorities.includes('DELETE_VISITE_TECHNIQUE')) {
      this.authoritiesUtilisateur.DELETE_VISITE_TECHNIQUE = true;
    }
    if (authorities.includes('VIEW_REFORME')) {
      this.authoritiesUtilisateur.VIEW_REFORME = true;
    }
    if (authorities.includes('ADD_REFORME')) {
      this.authoritiesUtilisateur.ADD_REFORME = true;
    }
    if (authorities.includes('MODIFY_REFORME')) {
      this.authoritiesUtilisateur.MODIFY_REFORME = true;
    }
    if (authorities.includes('DELETE_REFORME')) {
      this.authoritiesUtilisateur.DELETE_REFORME = true;
    }

    //Ordre de mission

    if (authorities.includes('VIEW_ORDRE_MISSION')) {
      this.authoritiesUtilisateur.VIEW_ORDRE_MISSION = true;
    }
    if (authorities.includes('ADD_ORDRE_MISSION')) {
      this.authoritiesUtilisateur.ADD_ORDRE_MISSION = true;
    }
    if (authorities.includes('MODIFY_ORDRE_MISSION')) {
      this.authoritiesUtilisateur.MODIFY_ORDRE_MISSION = true;
    }
    
    if (authorities.includes('DELETE_ORDRE_MISSION')) {
      this.authoritiesUtilisateur.DELETE_ORDRE_MISSION = true;
    }

    if (authorities.includes('VEHICULE_ORDRE_MISSION')) {
      this.authoritiesUtilisateur.VEHICULE_ORDRE_MISSION = true;
    }

    if (authorities.includes('CONFIRMER_ORDRE_MISSION')) {
      this.authoritiesUtilisateur.CONFIRMER_ORDRE_MISSION = true;
    }

    if (authorities.includes('VEHICULE_VEHICULE_DEPASSANT')) {
      this.authoritiesUtilisateur.VEHICULE_VEHICULE_DEPASSANT = true;
    }

    if (authorities.includes('DETAILS_VEHICULE_DEPASSANT')) {
      this.authoritiesUtilisateur.DETAILS_VEHICULE_DEPASSANT = true;
    }
    
    if (authorities.includes('DELETE_VEHICULE_DEPASSANT')) {
      this.authoritiesUtilisateur.DELETE_VEHICULE_DEPASSANT = true;
    }

    if (authorities.includes('VIEW_VEHICULE_DEPASSANT')) {
      this.authoritiesUtilisateur.VIEW_VEHICULE_DEPASSANT = true;
    }

    //Ordre de mission

    
    


//ACHAT
if (authorities.includes('MODIFY_BON_COMMANDE')) {
  this.authoritiesUtilisateur.MODIFY_BON_COMMANDE = true;
}
if (authorities.includes('DELETE_BON_COMMANDE')) {
  this.authoritiesUtilisateur.DELETE_BON_COMMANDE = true;
}
if (authorities.includes('VIEW_BON_COMMANDE')) {
  this.authoritiesUtilisateur.VIEW_BON_COMMANDE = true;
}
if (authorities.includes('ADD_BON_COMMANDE')) {
  this.authoritiesUtilisateur.ADD_BON_COMMANDE = true;
}
//END NACHAT
//STOCK

if (authorities.includes('CONFIRM_TRANSFERT_PARC_VERS_MAGASIN')) {
  this.authoritiesUtilisateur.CONFIRM_TRANSFERT_PARC_VERS_MAGASIN = true;
} 
if (authorities.includes('VALID_TRANSFERT_PARC_VERS_MAGASIN')) {
  this.authoritiesUtilisateur.VALID_TRANSFERT_PARC_VERS_MAGASIN = true;
} 
if (authorities.includes('ADD_TRANSFERT_PARC_VERS_MAGASIN')) {
  this.authoritiesUtilisateur.ADD_TRANSFERT_PARC_VERS_MAGASIN = true;
} 
if (authorities.includes('VIEW_TRANSFERT_PARC_VERS_MAGASIN')) {
  this.authoritiesUtilisateur.VIEW_TRANSFERT_PARC_VERS_MAGASIN = true;
} 
if (authorities.includes('DELETE_TRANSFERT_PARC_VERS_MAGASIN')) {
  this.authoritiesUtilisateur.DELETE_TRANSFERT_PARC_VERS_MAGASIN = true;
} 
if (authorities.includes('MODIFY_TRANSFERT_PARC_VERS_MAGASIN')) {
  this.authoritiesUtilisateur.MODIFY_TRANSFERT_PARC_VERS_MAGASIN = true;
} 


if (authorities.includes('VIEW_Bon_Travail_Sortie')) {
  this.authoritiesUtilisateur.VIEW_Bon_Travail_Sortie = true;
}
if (authorities.includes('DETAILS_Bon_Travail_Sortie')) {
  this.authoritiesUtilisateur.DETAILS_Bon_Travail_Sortie = true;
}
if (authorities.includes('VIEW_Bon_Transfert_vers_magasin')) {
  this.authoritiesUtilisateur.VIEW_Bon_Transfert_vers_magasin = true;
}
if (authorities.includes('CONFIRM_Bon_Transfert_vers_magasin')) {
  this.authoritiesUtilisateur.CONFIRM_Bon_Transfert_vers_magasin = true;
}


if (authorities.includes('VALIDER_Bon_Transfert_vers_magasin')) {
  this.authoritiesUtilisateur.VALIDER_Bon_Transfert_vers_magasin = true;
}

if (authorities.includes('MODIFY_Bon_Transfert_vers_magasin')) {
  this.authoritiesUtilisateur.MODIFY_Bon_Transfert_vers_magasin = true;
}
if (authorities.includes('DELETE_Bon_Transfert_vers_magasin')) {
  this.authoritiesUtilisateur.DELETE_Bon_Transfert_vers_magasin = true;
}
if (authorities.includes('ADD_Bon_Transfert_vers_magasin')) {
  this.authoritiesUtilisateur.ADD_Bon_Transfert_vers_magasin = true;
}
if (authorities.includes('VIEW_Bon_Sortie_Structure')) {
  this.authoritiesUtilisateur.VIEW_Bon_Sortie_Structure = true;
}
if (authorities.includes('VIEW_Reception_Fournisseur')) {
  this.authoritiesUtilisateur.VIEW_Reception_Fournisseur = true;
}
if (authorities.includes('DELETE_Reception_Fournisseur')) {
  this.authoritiesUtilisateur.DELETE_Reception_Fournisseur = true;
}
if (authorities.includes('DETAILS_Reception_Fournisseur')) {
  this.authoritiesUtilisateur.DETAILS_Reception_Fournisseur = true;
}


if (authorities.includes('VIEW_Reception_Atelier')) {
  this.authoritiesUtilisateur.VIEW_Reception_Atelier = true;
}
if (authorities.includes('VIEW_Transfert_magasin')) {
  this.authoritiesUtilisateur.VIEW_Reception_Fournisseur = true;
}
if (authorities.includes('VIEW_Retour_Structure')) {
  this.authoritiesUtilisateur.VIEW_Retour_Structure = true;
}
if (authorities.includes('DETAILS_Retour_Structure')) {
  this.authoritiesUtilisateur.DETAILS_Retour_Structure = true;
}


if (authorities.includes('VIEW_Reception_Atelier')) {
  this.authoritiesUtilisateur.VIEW_Reception_Atelier = true;
}
if (authorities.includes('VIEW_Transfert_magasin')) {
  this.authoritiesUtilisateur.VIEW_Reception_Fournisseur = true;
}
if (authorities.includes('VIEW_Retour_Structure')) {
  this.authoritiesUtilisateur.VIEW_Retour_Structure = true;
}
if (authorities.includes('DETAILS_Retour_Structure')) {
  this.authoritiesUtilisateur.DETAILS_Retour_Structure = true;
}


if (authorities.includes('DELETE_Retour_Structure')) {
  this.authoritiesUtilisateur.DELETE_Retour_Structure = true;
}
if (authorities.includes('ADD_Retour_Structure')) {
  this.authoritiesUtilisateur.ADD_Retour_Structure = true;
}
if (authorities.includes('VIEW_Inventaire_Stock')) {
  this.authoritiesUtilisateur.VIEW_Inventaire_Stock = true;
}
if (authorities.includes('DETAILS_Inventaire_Stock')) {
  this.authoritiesUtilisateur.DETAILS_Inventaire_Stock = true;
}


if (authorities.includes('DELETE_Inventaire_Stock')) {
  this.authoritiesUtilisateur.DELETE_Inventaire_Stock = true;
}
if (authorities.includes('ADD_Inventaire_Stock')) {
  this.authoritiesUtilisateur.ADD_Inventaire_Stock = true;
}
if (authorities.includes('VIEW_Regulation_Stock')) {
  this.authoritiesUtilisateur.VIEW_Regulation_Stock = true;
}
if (authorities.includes('DETAILS_Inventaire_Stock')) {
  this.authoritiesUtilisateur.DETAILS_Inventaire_Stock = true;
}


if (authorities.includes('DELETE_Regulation_Stock')) {
  this.authoritiesUtilisateur.DELETE_Regulation_Stock = true;
}
if (authorities.includes('ADD_Regulation_Stock')) {
  this.authoritiesUtilisateur.ADD_Regulation_Stock = true;
}
if (authorities.includes('VIEW_Regulation_Stock')) {
  this.authoritiesUtilisateur.VIEW_Regulation_Stock = true;
}
if (authorities.includes('DETAILS_Regulation_Stock')) {
  this.authoritiesUtilisateur.DETAILS_Regulation_Stock = true;
}

if (authorities.includes('VIEW_HISTORIQUE_REGULATION')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_REGULATION = true;
}
if (authorities.includes('DELETE_HISTORIQUE_REGULATION')) {
  this.authoritiesUtilisateur.DELETE_HISTORIQUE_REGULATION = true;
}


//REFERENTIEL
if (authorities.includes('VIEW_ARTICLES')) {
  this.authoritiesUtilisateur.VIEW_ARTICLES = true;
}
if (authorities.includes('ADD_ARTICLES')) {
  this.authoritiesUtilisateur.ADD_ARTICLES = true;
}
if (authorities.includes('MODIFY_ARTICLES')) {
  this.authoritiesUtilisateur.MODIFY_ARTICLES = true;
}
if (authorities.includes('DELETE_ARTICLES')) {
  this.authoritiesUtilisateur.DELETE_ARTICLES = true;
}
if (authorities.includes('VIEW_GOUVERNORATS')) {
  this.authoritiesUtilisateur.VIEW_GOUVERNORATS = true;
}
if (authorities.includes('ADD_GOUVERNORATS')) {
  this.authoritiesUtilisateur.ADD_GOUVERNORATS = true;
}
if (authorities.includes('MODIFY_GOUVERNORATS')) {
  this.authoritiesUtilisateur.MODIFY_GOUVERNORATS = true;
}
if (authorities.includes('DELETE_GOUVERNORATS')) {
  this.authoritiesUtilisateur.DELETE_GOUVERNORATS = true;
}
if (authorities.includes('VIEW_STATIONS_PEAGE')) {
  this.authoritiesUtilisateur.VIEW_STATIONS_PEAGE = true;
}
if (authorities.includes('ADD_STATIONS_PEAGE')) {
  this.authoritiesUtilisateur.ADD_STATIONS_PEAGE = true;
}
if (authorities.includes('MODIFY_STATIONS_PEAGE')) {
  this.authoritiesUtilisateur.MODIFY_STATIONS_PEAGE = true;
}
if (authorities.includes('DELETE_STATIONS_PEAGE')) {
  this.authoritiesUtilisateur.DELETE_STATIONS_PEAGE = true;
}
if (authorities.includes('VIEW_EXPERTS')) {
  this.authoritiesUtilisateur.VIEW_EXPERTS = true;
}
if (authorities.includes('ADD_EXPERTS')) {
  this.authoritiesUtilisateur.ADD_EXPERTS = true;
}
if (authorities.includes('MODIFY_EXPERTS')) {
  this.authoritiesUtilisateur.MODIFY_EXPERTS = true;
}
if (authorities.includes('DELETE_EXPERTS')) {
  this.authoritiesUtilisateur.DELETE_EXPERTS = true;
}
if (authorities.includes('VIEW_FOURNISSEURS')) {
  this.authoritiesUtilisateur.VIEW_FOURNISSEURS = true;
}
if (authorities.includes('ADD_FOURNISSEURS')) {
  this.authoritiesUtilisateur.ADD_FOURNISSEURS = true;
}
if (authorities.includes('MODIFY_FOURNISSEURS')) {
  this.authoritiesUtilisateur.MODIFY_FOURNISSEURS = true;
}
if (authorities.includes('DELETE_FOURNISSEURS')) {
  this.authoritiesUtilisateur.DELETE_FOURNISSEURS = true;
}
if (authorities.includes('VIEW_LIEUX_PARKING')) {
  this.authoritiesUtilisateur.VIEW_LIEUX_PARKING = true;
}
if (authorities.includes('ADD_LIEUX_PARKING')) {
  this.authoritiesUtilisateur.ADD_LIEUX_PARKING = true;
}
if (authorities.includes('MODIFY_LIEUX_PARKING')) {
  this.authoritiesUtilisateur.MODIFY_LIEUX_PARKING = true;
}
if (authorities.includes('DELETE_LIEUX_PARKING')) {
  this.authoritiesUtilisateur.DELETE_LIEUX_PARKING = true;
}
if (authorities.includes('VIEW_FAMILLES_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.VIEW_FAMILLES_OPERATIONS_REPARATION = true;
}
if (authorities.includes('ADD_FAMILLES_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.ADD_FAMILLES_OPERATIONS_REPARATION = true;
}
if (authorities.includes('MODIFY_FAMILLES_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.MODIFY_FAMILLES_OPERATIONS_REPARATION = true;
}
if (authorities.includes('DELETE_FAMILLES_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.DELETE_FAMILLES_OPERATIONS_REPARATION = true;
}
if (authorities.includes('VIEW_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.VIEW_OPERATIONS_REPARATION = true;
}
if (authorities.includes('ADD_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.ADD_OPERATIONS_REPARATION = true;
}
if (authorities.includes('MODIFY_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.MODIFY_OPERATIONS_REPARATION = true;
}
if (authorities.includes('DELETE_OPERATIONS_REPARATION')) {
  this.authoritiesUtilisateur.DELETE_OPERATIONS_REPARATION = true;
}
if (authorities.includes('VIEW_PROGRAMMES_ENTRETIENS_PREVENTIFS')) {
  this.authoritiesUtilisateur.VIEW_PROGRAMMES_ENTRETIENS_PREVENTIFS = true;
}
if (authorities.includes('ADD_PROGRAMMES_ENTRETIENS_PREVENTIFS')) {
  this.authoritiesUtilisateur.ADD_PROGRAMMES_ENTRETIENS_PREVENTIFS = true;
}
if (authorities.includes('MODIFY_PROGRAMMES_ENTRETIENS_PREVENTIFS')) {
  this.authoritiesUtilisateur.MODIFY_PROGRAMMES_ENTRETIENS_PREVENTIFS = true;
}
if (authorities.includes('DELETE_PROGRAMMES_ENTRETIENS_PREVENTIFS')) {
  this.authoritiesUtilisateur.DELETE_PROGRAMMES_ENTRETIENS_PREVENTIFS = true;
}
if (authorities.includes('VIEW_ANNEES')) {
  this.authoritiesUtilisateur.VIEW_ANNEES = true;
}
if (authorities.includes('ADD_ANNEES')) {
  this.authoritiesUtilisateur.ADD_ANNEES = true;
}
if (authorities.includes('DELETE_ANNEES')) {
  this.authoritiesUtilisateur.DELETE_ANNEES = true;
}
if (authorities.includes('VIEW_ENERGIES')) {
  this.authoritiesUtilisateur.VIEW_ENERGIES = true;
}
if (authorities.includes('ADD_ENERGIES')) {
  this.authoritiesUtilisateur.ADD_ENERGIES = true;
}
if (authorities.includes('MODIFY_ENERGIES')) {
  this.authoritiesUtilisateur.MODIFY_ENERGIES = true;
}
if (authorities.includes('DELETE_ENERGIES')) {
  this.authoritiesUtilisateur.DELETE_ENERGIES = true;
}
if (authorities.includes('ADD_TVA')) {
  this.authoritiesUtilisateur.ADD_TVA = true;
}
if (authorities.includes('MODIFY_TVA')) {
  this.authoritiesUtilisateur.MODIFY_TVA = true;
}
if (authorities.includes('DELETE_TVA')) {
  this.authoritiesUtilisateur.DELETE_TVA = true;
}
if (authorities.includes('VIEW_UNITES')) {
  this.authoritiesUtilisateur.VIEW_UNITES = true;
}
if (authorities.includes('ADD_UNITES')) {
  this.authoritiesUtilisateur.ADD_UNITES = true;
}
if (authorities.includes('DELETE_UNITES')) {
  this.authoritiesUtilisateur.DELETE_UNITES = true;
}
if (authorities.includes('VIEW_GENRES_VEHICULE')) {
  this.authoritiesUtilisateur.VIEW_GENRES_VEHICULE = true;
}
if (authorities.includes('ADD_GENRES_VEHICULE')) {
  this.authoritiesUtilisateur.ADD_GENRES_VEHICULE = true;
}
if (authorities.includes('MODIFY_GENRES_VEHICULE')) {
  this.authoritiesUtilisateur.MODIFY_GENRES_VEHICULE = true;
}
if (authorities.includes('DELETE_GENRES_VEHICULE')) {
  this.authoritiesUtilisateur.DELETE_GENRES_VEHICULE = true;
}
if (authorities.includes('VIEW_MARQUES_VEHICULE')) {
  this.authoritiesUtilisateur.VIEW_MARQUES_VEHICULE = true;
}
if (authorities.includes('ADD_MARQUES_VEHICULE')) {
  this.authoritiesUtilisateur.ADD_MARQUES_VEHICULE = true;
}
if (authorities.includes('MODIFY_MARQUES_VEHICULE')) {
  this.authoritiesUtilisateur.MODIFY_MARQUES_VEHICULE = true;
}
if (authorities.includes('DELETE_MARQUES_VEHICULE')) {
  this.authoritiesUtilisateur.DELETE_MARQUES_VEHICULE = true;
}
if (authorities.includes('VIEW_TYPES_VEHICULE')) {
  this.authoritiesUtilisateur.VIEW_TYPES_VEHICULE = true;
}
if (authorities.includes('ADD_TYPES_VEHICULE')) {
  this.authoritiesUtilisateur.ADD_TYPES_VEHICULE = true;
}
if (authorities.includes('MODIFY_TYPES_VEHICULE')) {
  this.authoritiesUtilisateur.MODIFY_TYPES_VEHICULE = true;
}
if (authorities.includes('DELETE_TYPES_VEHICULE')) {
  this.authoritiesUtilisateur.DELETE_TYPES_VEHICULE = true;
}
if (authorities.includes('VIEW_STRUCTURE_ADMINISTRATIVE')) {
  this.authoritiesUtilisateur.VIEW_STRUCTURE_ADMINISTRATIVE = true;
}
if (authorities.includes('ADD_STRUCTURE_ADMINISTRATIVE')) {
  this.authoritiesUtilisateur.ADD_STRUCTURE_ADMINISTRATIVE = true;
}
if (authorities.includes('MODIFY_STRUCTURE_ADMINISTRATIVE')) {
  this.authoritiesUtilisateur.MODIFY_STRUCTURE_ADMINISTRATIVE = true;
}
if (authorities.includes('DELETE_STRUCTURE_ADMINISTRATIVE')) {
  this.authoritiesUtilisateur.DELETE_STRUCTURE_ADMINISTRATIVE = true;
}
if (authorities.includes('VIEW_UNITE_GESTION_PARC')) {
  this.authoritiesUtilisateur.VIEW_UNITE_GESTION_PARC = true;
}
if (authorities.includes('ADD_UNITE_GESTION_PARC')) {
  this.authoritiesUtilisateur.ADD_UNITE_GESTION_PARC = true;
}
if (authorities.includes('MODIFY_UNITE_GESTION_PARC')) {
  this.authoritiesUtilisateur.MODIFY_UNITE_GESTION_PARC = true;
}
if (authorities.includes('DELETE_UNITE_GESTION_PARC')) {
  this.authoritiesUtilisateur.DELETE_UNITE_GESTION_PARC = true;
}
if (authorities.includes('VIEW_DETAILS_PERSONNELS')) {
  this.authoritiesUtilisateur.VIEW_DETAILS_PERSONNELS = true;
}
if (authorities.includes('ADD_DETAILS_PERSONNELS')) {
  this.authoritiesUtilisateur.ADD_DETAILS_PERSONNELS = true;
}
if (authorities.includes('MODIFY_DETAILS_PERSONNELS')) {
  this.authoritiesUtilisateur.MODIFY_DETAILS_PERSONNELS = true;
}
if (authorities.includes('DELETE_DETAILS_PERSONNELS')) {
  this.authoritiesUtilisateur.DELETE_DETAILS_PERSONNELS = true;
}
if (authorities.includes('VIEW_ETATS_STOCK')) {
  this.authoritiesUtilisateur.VIEW_ETATS_STOCK = true;
}
if (authorities.includes('ADD_ETATS_STOCK')) {
  this.authoritiesUtilisateur.ADD_ETATS_STOCK = true;
}
if (authorities.includes('MODIFY_ETATS_STOCK')) {
  this.authoritiesUtilisateur.MODIFY_ETATS_STOCK = true;
}
if (authorities.includes('DELETE_ETATS_STOCK')) {
  this.authoritiesUtilisateur.DELETE_ETATS_STOCK = true;
}
if (authorities.includes('VIEW_BENEFICIAIRES_EMPRUNTS')) {
  this.authoritiesUtilisateur.VIEW_BENEFICIAIRES_EMPRUNTS = true;
}
if (authorities.includes('ADD_BENEFICIAIRES_EMPRUNTS')) {
  this.authoritiesUtilisateur.ADD_BENEFICIAIRES_EMPRUNTS = true;
}
if (authorities.includes('MODIFY_BENEFICIAIRES_EMPRUNTS')) {
  this.authoritiesUtilisateur.MODIFY_BENEFICIAIRES_EMPRUNTS = true;
}
if (authorities.includes('DELETE_BENEFICIAIRES_EMPRUNTS')) {
  this.authoritiesUtilisateur.DELETE_BENEFICIAIRES_EMPRUNTS = true;
}
//REFERENTIEL
//EXPLOITATION
if (authorities.includes('VIEW_RESERVATION')) {
  this.authoritiesUtilisateur.VIEW_RESERVATION = true;
} 
if (authorities.includes('VIEW_VEHICULE_RESERVATION')) {
  this.authoritiesUtilisateur.VIEW_VEHICULE_RESERVATION = true;
} 
if (authorities.includes('DELETE_RESERVATION')) {
  this.authoritiesUtilisateur.DELETE_RESERVATION = true;
}
if (authorities.includes('MODIFY_RESERVATION')) {
  this.authoritiesUtilisateur.MODIFY_RESERVATION = true;
}
if (authorities.includes('ADD_RESERVATION')) {
  this.authoritiesUtilisateur.ADD_RESERVATION = true;
}
if (authorities.includes('CONFIRMER_RESERVATION')) {
  this.authoritiesUtilisateur.CONFIRMER_RESERVATION = true;
}
if (authorities.includes('VIEW_VEHICULE_EMPRUNT')) {
  this.authoritiesUtilisateur.VIEW_VEHICULE_EMPRUNT = true;
}
if (authorities.includes('DELETE_EMPRUNT')) {
  this.authoritiesUtilisateur.DELETE_EMPRUNT = true;
}
if (authorities.includes('MODIFY_EMPRUNT')) {
  this.authoritiesUtilisateur.MODIFY_EMPRUNT = true;
} 
if (authorities.includes('ADD_EMPRUNT')) {
  this.authoritiesUtilisateur.ADD_EMPRUNT = true;
}
 if (authorities.includes('VIEW_EMPRUNT')) {
  this.authoritiesUtilisateur.VIEW_EMPRUNT = true;
} 
if (authorities.includes('VIEW_VEHICULE_SINISTRE')) {
  this.authoritiesUtilisateur.VIEW_VEHICULE_SINISTRE = true;
} 
if (authorities.includes('DELETE_SINISTRE')) {
  this.authoritiesUtilisateur.DELETE_SINISTRE = true;
}
 if (authorities.includes('MODIFY_SINISTRE')) {
  this.authoritiesUtilisateur.MODIFY_SINISTRE = true;
}
 if (authorities.includes('ADD_SINISTRE')) {
  this.authoritiesUtilisateur.ADD_SINISTRE = true;
}
 if (authorities.includes('VIEW_SINISTRE')) {
  this.authoritiesUtilisateur.VIEW_SINISTRE = true;
} 
if (authorities.includes('DELETE_LOCATION')) {
  this.authoritiesUtilisateur.DELETE_LOCATION = true;
}
 if (authorities.includes('MODIFY_LOCATION')) {
  this.authoritiesUtilisateur.MODIFY_LOCATION = true;
} 
if (authorities.includes('ADD_LOCATION')) {
  this.authoritiesUtilisateur.ADD_LOCATION = true;
} 
if (authorities.includes('VIEW_LOCATION')) {
  this.authoritiesUtilisateur.VIEW_LOCATION = true;
}
if (authorities.includes('CONFIRMER_EMPRUNT')) {
  this.authoritiesUtilisateur.CONFIRMER_EMPRUNT = true;
}

//EXPLOITATION
 //CARBURANT : CARTE PLAFOND


 if (authorities.includes('DELETE_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.DELETE_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
}

if (authorities.includes('VIEW_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
}

if (authorities.includes('CONFIRMATION_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.CONFIRMATION_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
}

if (authorities.includes('DELETE_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.DELETE_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
}

if (authorities.includes('MODIFY_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.MODIFY_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
}

if (authorities.includes('VIEW_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
}

if (authorities.includes('ADD_DEMANDE_ANNULATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_ANNULATION_CARTE_PLAFOND = true;
}

if (authorities.includes('DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND = true;
}

if (authorities.includes('VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_PLAFOND = true;
}

if (authorities.includes('CONFIRMATION_DECLARATION_PERTE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.CONFIRMATION_DECLARATION_PERTE_CARTE_PLAFOND = true;
}

if (authorities.includes('ADD_DECLARATION_PERTE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.ADD_DECLARATION_PERTE_CARTE_PLAFOND = true;
}

if (authorities.includes('DELETE_DECLARATION_PERTE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.DELETE_DECLARATION_PERTE_CARTE_PLAFOND = true;
}

if (authorities.includes('MODIFY_DECLARATION_PERTE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.MODIFY_DECLARATION_PERTE_CARTE_PLAFOND = true;
}

if (authorities.includes('VIEW_DECLARATION_PERTE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VIEW_DECLARATION_PERTE_CARTE_PLAFOND = true;
}

if (authorities.includes('VEHICULE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VEHICULE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}

if (authorities.includes('DELETE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.DELETE_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}

if (authorities.includes('VIEW_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}

if (authorities.includes('VALIDATION_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VALIDATION_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}

if (authorities.includes('CONFIRM_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.CONFIRM_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}

if (authorities.includes('ADD_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}

if (authorities.includes('DELETE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.DELETE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}
if (authorities.includes(' VEHICULE_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VEHICULE_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}
if (authorities.includes('VIEW_DEMANDE_AFFECTATION_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_AFFECTATION_CARTE_PLAFOND = true;
}

if (authorities.includes('ADD_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.ADD_CARTE_PLAFOND = true;
}

if (authorities.includes('DELETE_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.DELETE_CARTE_PLAFOND = true;
}

if (authorities.includes('MODIFY_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.MODIFY_CARTE_PLAFOND = true;
}

if (authorities.includes('VIEW_CARTE_PLAFOND')) {
  this.authoritiesUtilisateur.VIEW_CARTE_PLAFOND = true;
}

 //CARBURANT : CARTE PLAFOND

 //CARBURANT : CARTE JOCKER
 if (authorities.includes('DELETE_DEMANDE_QUOTA_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.DELETE_DEMANDE_QUOTA_CARTE_JOCKER = true;
}
if (authorities.includes('MODIFY_DEMANDE_QUOTA_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.MODIFY_DEMANDE_QUOTA_CARTE_JOCKER = true;
}
if (authorities.includes('ADD_DEMANDE_QUOTA_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_QUOTA_CARTE_JOCKER = true;
}
if (authorities.includes('VALIDATION_DEMANDE_QUOTA_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VALIDATION_DEMANDE_QUOTA_CARTE_JOCKER = true;
}
if (authorities.includes('CONFIRMATION_DEMANDE_QUOTA_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.CONFIRMATION_DEMANDE_QUOTA_CARTE_JOCKER = true;
}
if (authorities.includes('DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.DELETE_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER = true;
}
if (authorities.includes('VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_DECLARATION_PERTE_CARTE_JOCKER = true;
}
if (authorities.includes('VIEW_DECLARATION_PERTE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VIEW_DECLARATION_PERTE_CARTE_JOCKER = true;
}
if (authorities.includes('CONFIRMATION_DECLARATION_PERTE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.CONFIRMATION_DECLARATION_PERTE_CARTE_JOCKER = true;
}
if (authorities.includes('MODIFY_DECLARATION_PERTE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.MODIFY_DECLARATION_PERTE_CARTE_JOCKER = true;
}
if (authorities.includes('DELETE_DECLARATION_PERTE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.DELETE_DECLARATION_PERTE_CARTE_JOCKER = true;
}
if (authorities.includes('ADD_DECLARATION_PERTE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.ADD_DECLARATION_PERTE_CARTE_JOCKER = true;
}
if (authorities.includes('DELETE_DEMANDE_DESAFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.DELETE_DEMANDE_DESAFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('MODIFY_DEMANDE_DESAFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.MODIFY_DEMANDE_DESAFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('VIEW_DEMANDE_DESAFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_DESAFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('ADD_DEMANDE_DESAFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_DESAFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('CONFIRMATION_DEMANDE_DESAFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.CONFIRMATION_DEMANDE_DESAFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('DELETE_DEMANDE_AFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.DELETE_DEMANDE_AFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('VEHICULE_DEMANDE_AFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VEHICULE_DEMANDE_AFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('ADD_DEMANDE_AFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.ADD_DEMANDE_AFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('MODIFY_DEMANDE_AFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.MODIFY_DEMANDE_AFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('VIEW_DEMANDE_AFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_AFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('VALIDATION_DEMANDE_AFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VALIDATION_DEMANDE_AFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('CONFIRMATION_DEMANDE_AFFECTATION_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.CONFIRMATION_DEMANDE_AFFECTATION_CARTE_JOCKER = true;
}
if (authorities.includes('ADD_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.ADD_CARTE_JOCKER = true;
}
if (authorities.includes('DELETE_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.DELETE_CARTE_JOCKER = true;
}
if (authorities.includes('MODIFY_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.MODIFY_CARTE_JOCKER = true;
}
if (authorities.includes('VIEW_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VIEW_CARTE_JOCKER = true;
}
if (authorities.includes('VIEW_DEMANDE_QUOTA_CARTE_JOCKER')) {
  this.authoritiesUtilisateur.VIEW_DEMANDE_QUOTA_CARTE_JOCKER = true;
}

        
 //CARBURANT : CARTE JOCKER   


 // CARBURANT : Distribution de carburant

if (authorities.includes('VIEW_SUIVI')) {
  this.authoritiesUtilisateur.VIEW_SUIVI = true;
}
if (authorities.includes('ADD_SUIVI')) {
  this.authoritiesUtilisateur.ADD_SUIVI = true;
}
if (authorities.includes('VIEW_BON_CARBURANT_BON')) {
  this.authoritiesUtilisateur.VIEW_BON_CARBURANT_BON = true;
}
if (authorities.includes('ADD_BON_CARBURANT_BON')) {
  this.authoritiesUtilisateur.ADD_BON_CARBURANT_BON = true;
}
if (authorities.includes('CONFIRMER_ETAT_MENSUEL')) {
  this.authoritiesUtilisateur.CONFIRMER_ETAT_MENSUEL = true;
}
if (authorities.includes('VALIDER_ETAT_MENSUEL')) {
  this.authoritiesUtilisateur.VALIDER_ETAT_MENSUEL = true;
}
if (authorities.includes('VEHICULE_ETAT_MENSUEL')) {
  this.authoritiesUtilisateur.VEHICULE_ETAT_MENSUEL = true;
}
if (authorities.includes('VIEW_ETAT_MENSUEL')) {
  this.authoritiesUtilisateur.VIEW_ETAT_MENSUEL = true;
}
if (authorities.includes('DELETE_ETAT_MENSUEL')) {
  this.authoritiesUtilisateur.DELETE_ETAT_MENSUEL = true;
}
if (authorities.includes('MODIFY_ETAT_MENSUEL')) {
  this.authoritiesUtilisateur.MODIFY_ETAT_MENSUEL = true;
}
if (authorities.includes('ADD_ETAT_MENSUEL')) {
  this.authoritiesUtilisateur.ADD_ETAT_MENSUEL = true;
}
if (authorities.includes('VIEW_RETOUR_CARBURANT')) {
  this.authoritiesUtilisateur.VIEW_RETOUR_CARBURANT = true;
}
if (authorities.includes('ADD_RETOUR_CARBURANT')) {
  this.authoritiesUtilisateur.ADD_RETOUR_CARBURANT = true;
}
if (authorities.includes('DETAIL_TRANSFERT_PARC')) {
  this.authoritiesUtilisateur.DETAIL_TRANSFERT_PARC = true;
}
if (authorities.includes('VIEW_TRANSFERT_PARC')) {
  this.authoritiesUtilisateur.VIEW_TRANSFERT_PARC = true;
}
if (authorities.includes('ADD_TRANSFERT_PARC')) {
  this.authoritiesUtilisateur.ADD_TRANSFERT_PARC = true;
}
if (authorities.includes('VEHICULE_DESTRIBUTION_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.VEHICULE_DESTRIBUTION_CARBURANT_COMPENSATION = true;
}
if (authorities.includes('VIEW_DESTRIBUTION_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.VIEW_DESTRIBUTION_CARBURANT_COMPENSATION = true;
}
if (authorities.includes('DELETE_DESTRIBUTION_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.DELETE_DESTRIBUTION_CARBURANT_COMPENSATION = true;
}
if (authorities.includes('MODIFY_DESTRIBUTION_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.MODIFY_DESTRIBUTION_CARBURANT_COMPENSATION = true;
}
if (authorities.includes('ADD_DESTRIBUTION_CARBURANT_COMPENSATION')) {
  this.authoritiesUtilisateur.ADD_DESTRIBUTION_CARBURANT_COMPENSATION = true;
}


//CARBURANT : RECHARGE DE QUOTA MENSUEL 

if (authorities.includes('CONFIRM_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.CONFIRM_RECHARGE_QUOTA_MENSUEL = true;
} 
if (authorities.includes('VALID_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.VALID_RECHARGE_QUOTA_MENSUEL = true;
} 
if (authorities.includes('ADD_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.ADD_RECHARGE_QUOTA_MENSUEL = true;
} 
if (authorities.includes('VIEW_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.VIEW_RECHARGE_QUOTA_MENSUEL = true;
} 
//CARBURANT : RECHARGE DE QUOTA MENSUEL 

//CARBURANT : historique RECHARGE DE QUOTA MENSUEL
if (authorities.includes('VIEW_HISTORIQUE_RECHARGE_QUOTA_MENSUEL')) {
  this.authoritiesUtilisateur.VIEW_HISTORIQUE_RECHARGE_QUOTA_MENSUEL = true;
} 
//CARBURANT : historique RECHARGE DE QUOTA MENSUEL 

if (authorities.includes('VEHICULE_DESTRIBUTION_CARBURANT_SERVICE')) {
  this.authoritiesUtilisateur.VEHICULE_DESTRIBUTION_CARBURANT_SERVICE = true;
}
if (authorities.includes('VIEW_DESTRIBUTION_CARBURANT_SERVICE')) {
  this.authoritiesUtilisateur.VIEW_DESTRIBUTION_CARBURANT_SERVICE = true;
}
if (authorities.includes('DELETE_DESTRIBUTION_CARBURANT_SERVICE')) {
  this.authoritiesUtilisateur.DELETE_DESTRIBUTION_CARBURANT_SERVICE = true;
}
if (authorities.includes('MODIFY_DESTRIBUTION_CARBURANT_SERVICE')) {
  this.authoritiesUtilisateur.MODIFY_DESTRIBUTION_CARBURANT_SERVICE = true;
}
if (authorities.includes('ADD_DESTRIBUTION_CARBURANT_SERVICE')) {
  this.authoritiesUtilisateur.ADD_DESTRIBUTION_CARBURANT_SERVICE = true;
}
if (authorities.includes('VIEW_DISTRIBUTION_CARBURANT_VEHICULE')) {
  this.authoritiesUtilisateur.VIEW_DISTRIBUTION_CARBURANT_VEHICULE = true;
}
if (authorities.includes('DELETE_DISTRIBUTION_CARBURANT_VEHICULE')) {
  this.authoritiesUtilisateur.DELETE_DISTRIBUTION_CARBURANT_VEHICULE = true;
}
if (authorities.includes('MODIFY_DISTRIBUTION_CARBURANT_VEHICULE')) {
  this.authoritiesUtilisateur.MODIFY_DISTRIBUTION_CARBURANT_VEHICULE = true;
}
if (authorities.includes('ADD_DISTRIBUTION_CARBURANT_VEHICULE')) {
  this.authoritiesUtilisateur.ADD_DISTRIBUTION_CARBURANT_VEHICULE = true;
}
if (authorities.includes('VEHICULE_DISTRIBUTION_CARBURANT_FONCTION')) {
  this.authoritiesUtilisateur.VEHICULE_DISTRIBUTION_CARBURANT_FONCTION = true;
}
if (authorities.includes('VIEW_DISTRIBUTION_CARBURANT_FONCTION')) {
  this.authoritiesUtilisateur.VIEW_DISTRIBUTION_CARBURANT_FONCTION = true;
}
if (authorities.includes('DELETE_DISTRIBUTION_CARBURANT_FONCTION')) {
  this.authoritiesUtilisateur.DELETE_DISTRIBUTION_CARBURANT_FONCTION = true;
}
if (authorities.includes('MODIFY_DISTRIBUTION_CARBURANT_FONCTION')) {
  this.authoritiesUtilisateur.MODIFY_DISTRIBUTION_CARBURANT_FONCTION = true;
}
if (authorities.includes('ADD_DISTRIBUTION_CARBURANT_FONCTION')) {
  this.authoritiesUtilisateur.ADD_DISTRIBUTION_CARBURANT_FONCTION = true;
}
// CARBURANT : Distribution de carburant


if (authorities.includes('REOUVRIR_SORTIE_VEHICULE')) {
  this.authoritiesUtilisateur.REOUVRIR_SORTIE_VEHICULE = true;
}
if (authorities.includes('ANNULATION_DEMANDE_INTERVENTION')) {
  this.authoritiesUtilisateur.ANNULATION_DEMANDE_INTERVENTION = true;
}
if (authorities.includes('VEHICULE_DEMANDE_INTERVENTION')) {
  this.authoritiesUtilisateur.VEHICULE_DEMANDE_INTERVENTION = true;
}
if (authorities.includes('RECU_DEMANDE_INTERVENTION')) {
  this.authoritiesUtilisateur.RECU_DEMANDE_INTERVENTION = true;
}


  }

  saveUserAuthorities() {
    localStorage.setItem('User_Authorities', JSON.stringify(this.getAuthoritiesUtilisateur()));
  }

  saveCurrentUser(matricule: string, mot2passe: string) {
    const currentUser: Utilisateur = {matricule: '', mot2passe: ''};
    currentUser.matricule = matricule;
    currentUser.mot2passe = mot2passe;
    if (localStorage.getItem('currentUser')) {
      localStorage.removeItem('currentUser');
    }
    this.encryptInfo = encodeURIComponent(CryptoJS.AES.encrypt(JSON.stringify(currentUser), 'secret key 123').toString());
    localStorage.setItem('currentUser', this.encryptInfo);
    console.log("encryptInfo");
   console.log(this.encryptInfo);

    //Decrypt Info
    var deData= CryptoJS.AES.decrypt(decodeURIComponent(this.encryptInfo), 'secret key 123'); 
    this.decryptedInfo = JSON.parse(deData.toString(CryptoJS.enc.Utf8));
 
    console.log("decryptedInfo");
    console.log(this.decryptedInfo);

  }

  neSeSouvenirDeMoi() {
    localStorage.removeItem('encryptInfo');
  }

  seSouvenirDeMoi() {
    if (localStorage.getItem('encryptInfo')) {
      return JSON.parse(localStorage.getItem('encryptInfo'));
    }
  }


}
